package main

import (
	"archive/zip"
	"bufio"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

// version is injected at release time via:
//
//	go build -ldflags "-X main.version=v1.2.3"
//
// Local/dev builds report "dev".
var version = "dev"

// Tool is deliberately generic. Provider owns lifecycle/state semantics;
// Command is prepended inside the container. An empty Command means: use the
// image ENTRYPOINT as-is (handy for images such as ghcr.io/jqlang/jq).
type Tool struct {
	Name           string
	Image          string
	Provider       string // stateless, python
	Role           string // provider-specific: python, pip
	Command        []string
	ArgsPrefix     []string
	PathNext       []string // options whose following argv is a path
	PathEquals     []string // options of the form --opt=PATH
	PathLast       bool     // final non-option argv is a path
	PathLastIfAny  []string // apply PathLast only when any listed argv is present
	EnvPrefixes    []string // host env var prefixes passed into the container
	EnvNames       []string // exact host env var names passed into the container
	EnvSet         []string // literal NAME=VALUE entries injected into the container
	ProjectMarkers []string // tool/provider-specific project root markers
	StateGroup     string   // stable namespace shared by related stateful tools
	ProjectVolumes []string // NAME:CONTAINER_PATH, project-scoped named volumes
	SharedVolumes  []string // NAME:CONTAINER_PATH, shared named volumes
}

type Registry struct {
	SchemaVersion int
	Tools         map[string]Tool
}

type LockEntry struct {
	Configured string
	Resolved   string
	Digest     string
}

type LockFile struct {
	Version int
	Images  map[string]LockEntry // keyed by configured image reference
}

const defaultRegistryTOML = `# container-bin tool registry
schema_version = 1
# Generated by cb. Edit this file, then run: cb install
#
# provider = "stateless" => disposable container, no tool-specific state
# provider = "python"    => legacy Python provider: project /venv + shared pip cache
# provider = "stateful"  => generic declarative persistent volumes
#
# Tool-semantics rules:
# path_next   = ["-i"]       => argv immediately following this option is a host path
# path_equals = ["-chdir"]   => -chdir=HOST_PATH is rewritten safely
# path_last   = true          => final non-option argv is treated as a host path
# path_last_if_any = ["-i"]  => path_last only applies if one of these argv exists
# env_prefixes / env_names   => explicitly pass selected host environment variables
# env_set                    => literal NAME=VALUE entries injected into the container
# project_markers            => files/dirs used to find this tool's project root
# state_group                => namespace shared by related stateful shims
# project_volumes            => ["name:/container/path"] scoped by project root
# shared_volumes             => ["name:/container/path"] shared across projects

[tools.python]
image = "python:3.13-slim"
provider = "python"
role = "python"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.python3]
image = "python:3.13-slim"
provider = "python"
role = "python"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.pip]
image = "python:3.13-slim"
provider = "python"
role = "pip"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.pip3]
image = "python:3.13-slim"
provider = "python"
role = "pip"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.jq]
image = "ghcr.io/jqlang/jq:latest"
provider = "stateless"

[tools.yq]
image = "mikefarah/yq:latest"
provider = "stateless"
env_names = ["NO_COLOR"]

[tools.terraform]
image = "hashicorp/terraform:latest"
provider = "stateless"
path_equals = ["-chdir"]
env_prefixes = ["TF_", "AWS_", "ARM_", "AZURE_", "GOOGLE_", "GCLOUD_", "CLOUDFLARE_", "HCLOUD_", "DIGITALOCEAN_", "LINODE_", "OVH_", "VAULT_", "CONSUL_"]
env_names = ["HOME", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.ffmpeg]
image = "lscr.io/linuxserver/ffmpeg:latest"
provider = "stateless"
# Intentionally no forced path rules: FFmpeg inputs can also be URLs, pipes,
# devices and lavfi expressions. Generic host-path detection is safer.

[tools.node]
image = "node:24-slim"
provider = "stateful"
command = ["node"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "NPM_CONFIG_REGISTRY", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npm]
image = "node:24-slim"
provider = "stateful"
command = ["npm"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npx]
image = "node:24-slim"
provider = "stateful"
command = ["npx"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]
`

func main() {
	reg, cfgPath, err := loadRegistry()
	if err != nil {
		fatalf("registry: %v", err)
	}

	invoked := invokedName(os.Args[0])
	if invoked != "cb" && invoked != "container-bin" && !strings.HasPrefix(invoked, "cb-v") {
		tool, ok := reg.Tools[invoked]
		if !ok {
			fatalf("no tool profile for %q (registry: %s)", invoked, cfgPath)
		}
		code, err := runTool(tool, os.Args[1:])
		if err != nil {
			fatalf("%v", err)
		}
		os.Exit(code)
	}

	if len(os.Args) < 2 {
		usage(cfgPath)
		return
	}
	switch os.Args[1] {
	case "install":
		if err := withMutationLock(cfgPath, func() error {
			if err := ensureRegistryFile(cfgPath); err != nil {
				return err
			}
			if err := appendMissingDefaultTools(cfgPath); err != nil {
				return err
			}
			// Reload in case the file was just created or upgraded.
			reg, _, err = loadRegistry()
			if err != nil {
				return err
			}
			return installShims(reg)
		}); err != nil {
			fatalf("install: %v", err)
		}
	case "setup":
		if err := withMutationLock(cfgPath, func() error {
			return setupCommand(cfgPath)
		}); err != nil {
			fatalf("setup: %v", err)
		}
	case "doctor":
		if err := doctor(reg, cfgPath); err != nil {
			fatalf("doctor: %v", err)
		}
	case "backup":
		if err := backupCommand(cfgPath, os.Args[2:]); err != nil {
			fatalf("backup: %v", err)
		}
	case "restore":
		if err := withMutationLock(cfgPath, func() error {
			return restoreCommand(cfgPath, os.Args[2:])
		}); err != nil {
			fatalf("restore: %v", err)
		}
	case "self-test":
		if err := selfTestCommand(reg); err != nil {
			fatalf("self-test: %v", err)
		}
	case "list":
		listTools(reg, cfgPath)
	case "trace":
		if err := traceTool(reg, os.Args[2:]); err != nil {
			fatalf("trace: %v", err)
		}
	case "env":
		if err := showEnv(reg); err != nil {
			fatalf("env: %v", err)
		}
	case "state":
		if err := showState(reg); err != nil {
			fatalf("state: %v", err)
		}
	case "inspect":
		if err := inspectTool(reg, os.Args[2:]); err != nil {
			fatalf("inspect: %v", err)
		}
	case "gc":
		if err := gcState(reg, os.Args[2:]); err != nil {
			fatalf("gc: %v", err)
		}
	case "expose":
		if err := withMutationLock(cfgPath, func() error {
			reg, _, err := loadRegistry()
			if err != nil {
				return err
			}
			return exposeTool(reg, cfgPath, os.Args[2:])
		}); err != nil {
			fatalf("expose: %v", err)
		}
	case "unexpose":
		if err := withMutationLock(cfgPath, func() error {
			reg, _, err := loadRegistry()
			if err != nil {
				return err
			}
			return unexposeTools(reg, cfgPath, os.Args[2:])
		}); err != nil {
			fatalf("unexpose: %v", err)
		}
	case "uninstall":
		if err := withMutationLock(cfgPath, func() error {
			reg, _, err := loadRegistry()
			if err != nil {
				return err
			}
			return uninstallTools(reg, cfgPath, os.Args[2:])
		}); err != nil {
			fatalf("uninstall: %v", err)
		}
	case "lock":
		if err := withMutationLock(cfgPath, func() error {
			reg, _, err := loadRegistry()
			if err != nil {
				return err
			}
			return lockCommand(reg, cfgPath, os.Args[2:])
		}); err != nil {
			fatalf("lock: %v", err)
		}
	case "update":
		if err := withMutationLock(cfgPath, func() error {
			reg, _, err := loadRegistry()
			if err != nil {
				return err
			}
			return updateCommand(reg, cfgPath, os.Args[2:])
		}); err != nil {
			fatalf("update: %v", err)
		}
	case "config":
		fmt.Println(cfgPath)
	case "version", "--version", "-V":
		fmt.Printf("container-bin %s\n", version)
	default:
		usage(cfgPath)
		osExit(exitUsage)
	}
}

// invokedName derives the dispatch name from argv[0]. Windows filenames are
// case-insensitive, so both base and extension are lowered before trimming —
// cmd.exe can hand us PYTHON.EXE, which must still dispatch as "python".
func invokedName(argv0 string) string {
	base := strings.ToLower(filepath.Base(argv0))
	return strings.TrimSuffix(base, filepath.Ext(base))
}

func usage(cfg string) {
	fmt.Printf(`container-bin (cb) %s — Docker-backed Windows CLI shims

Commands:
  cb setup     initialize/upgrade registry, install shims, then run doctor
  cb install   create/update shims from the tool registry
  cb doctor    validate Docker, PATH, shims, registry, lock and managed volumes
  cb backup    back up registry + lock to a zip
  cb restore   validate/restore a backup (dry-run unless --apply)
  cb self-test run offline end-to-end compatibility checks
  cb list      list configured tool profiles
  cb trace     show raw/normalized/mapped argv for a tool without running it
  cb env       show project root and Python environment selected for cwd
  cb state     list container-bin Docker volumes and mark current/shared state
  cb inspect   show a tool profile plus resolved project/state information
  cb gc        dry-run cleanup; supports --orphans for labeled missing projects
  cb expose    expose binaries from a managed global tool store (npm)
  cb unexpose  remove dynamically exposed tool profiles/shims
  cb uninstall remove custom tool profiles/shims
  cb lock      create/check immutable image digest lockfile
  cb update    explicitly refresh one or all locked images
  cb config    print registry path
  cb version   print container-bin version

Registry:
  %s
`, version, cfg)
}

func defaultRegistry() Registry {
	reg, err := parseRegistryTOML(defaultRegistryTOML)
	if err != nil {
		panic("invalid built-in registry: " + err.Error())
	}
	return reg
}

func registryPath() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	exe, err = filepath.Abs(exe)
	if err != nil {
		return "", err
	}
	return filepath.Join(filepath.Dir(exe), "container-bin.toml"), nil
}

func ensureRegistryFile(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	return atomicWriteFile(path, []byte(defaultRegistryTOML), 0644)
}

// appendMissingDefaultTools upgrades an existing registry non-destructively.
// Existing tool sections are never rewritten; missing built-in sections are
// appended, preserving user profiles and comments (e.g. jq2 from earlier tests).
func appendMissingDefaultTools(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	reg, err := parseRegistryTOML(string(data))
	if err != nil {
		return err
	}
	defaults := defaultToolSections()
	var names []string
	for name := range defaults {
		if _, exists := reg.Tools[name]; !exists {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return nil
	}
	sort.Strings(names)
	var b strings.Builder
	b.Write(data)
	if len(data) > 0 && data[len(data)-1] != '\n' {
		b.WriteByte('\n')
	}
	b.WriteString("\n# Added by container-bin " + version + "\n")
	for _, name := range names {
		b.WriteString(defaults[name])
	}
	return atomicWriteFile(path, []byte(b.String()), 0644)
}

func defaultToolSections() map[string]string {
	sections := map[string]string{}
	var current string
	var b strings.Builder
	flush := func() {
		if current != "" {
			sections[current] = "\n" + b.String()
		}
		b.Reset()
	}
	for _, line := range strings.Split(defaultRegistryTOML, "\n") {
		trim := strings.TrimSpace(line)
		if strings.HasPrefix(trim, "[tools.") && strings.HasSuffix(trim, "]") {
			flush()
			current = strings.TrimSuffix(strings.TrimPrefix(trim, "[tools."), "]")
		}
		if current != "" {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	flush()
	return sections
}

func loadRegistry() (Registry, string, error) {
	path, err := registryPath()
	if err != nil {
		return Registry{}, "", err
	}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		rec, err := recoverFromBackup(path, validateRegistryBackup)
		if err != nil {
			return Registry{}, path, err
		}
		if !rec {
			return defaultRegistry(), path, nil
		}
		data, err = os.ReadFile(path)
		if err != nil {
			return Registry{}, path, err
		}
	} else if err != nil {
		return Registry{}, path, err
	}
	reg, err := parseRegistryTOML(string(data))
	return reg, path, err
}

// parseRegistryTOML intentionally supports only the tiny TOML subset used by
// container-bin's registry: [tools.NAME], quoted strings and arrays of quoted
// strings. Rejecting unknown syntax is safer than silently misreading config.
func parseRegistryTOML(s string) (Registry, error) {
	reg := Registry{SchemaVersion: 1, Tools: map[string]Tool{}}
	var current *Tool
	scanner := bufio.NewScanner(strings.NewReader(s))
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(stripComment(scanner.Text()))
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "[") {
			if !strings.HasSuffix(line, "]") {
				return reg, fmt.Errorf("line %d: malformed section", lineNo)
			}
			sec := strings.TrimSpace(line[1 : len(line)-1])
			if !strings.HasPrefix(sec, "tools.") || len(sec) <= len("tools.") {
				return reg, fmt.Errorf("line %d: only [tools.NAME] sections are supported", lineNo)
			}
			name := strings.ToLower(strings.TrimSpace(strings.TrimPrefix(sec, "tools.")))
			if !validToolName(name) {
				return reg, fmt.Errorf("line %d: invalid tool name %q", lineNo, name)
			}
			if reservedToolName(name) {
				return reg, fmt.Errorf("line %d: tool name %q is reserved (would collide with cb itself or a Windows device name); rename or delete the [tools.%s] section in the registry file to recover", lineNo, name, name)
			}
			if _, dup := reg.Tools[name]; dup {
				return reg, fmt.Errorf("line %d: duplicate [tools.%s] section", lineNo, name)
			}
			t := Tool{Name: name, Provider: "stateless"}
			reg.Tools[name] = t
			current = &t
			continue
		}
		if current == nil {
			kv := strings.SplitN(line, "=", 2)
			if len(kv) == 2 && strings.TrimSpace(kv[0]) == "schema_version" {
				v, err := strconv.Atoi(strings.TrimSpace(kv[1]))
				if err != nil || v < 1 {
					return reg, fmt.Errorf("line %d: invalid schema_version", lineNo)
				}
				if v > 1 {
					return reg, fmt.Errorf("line %d: registry schema_version %d is newer than this cb supports (max 1)", lineNo, v)
				}
				reg.SchemaVersion = v
				continue
			}
			return reg, fmt.Errorf("line %d: key outside [tools.NAME] section", lineNo)
		}
		kv := strings.SplitN(line, "=", 2)
		if len(kv) != 2 {
			return reg, fmt.Errorf("line %d: expected key = value", lineNo)
		}
		key := strings.TrimSpace(kv[0])
		value := strings.TrimSpace(kv[1])
		t := reg.Tools[current.Name]
		switch key {
		case "image":
			v, err := parseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d image: %w", lineNo, err)
			}
			t.Image = v
		case "provider":
			v, err := parseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d provider: %w", lineNo, err)
			}
			t.Provider = strings.ToLower(v)
		case "role":
			v, err := parseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d role: %w", lineNo, err)
			}
			t.Role = strings.ToLower(v)
		case "command":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d command: %w", lineNo, err)
			}
			t.Command = v
		case "args_prefix":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d args_prefix: %w", lineNo, err)
			}
			t.ArgsPrefix = v
		case "path_next":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_next: %w", lineNo, err)
			}
			t.PathNext = v
		case "path_equals":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_equals: %w", lineNo, err)
			}
			t.PathEquals = v
		case "path_last":
			v, err := parseBool(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_last: %w", lineNo, err)
			}
			t.PathLast = v
		case "path_last_if_any":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_last_if_any: %w", lineNo, err)
			}
			t.PathLastIfAny = v
		case "env_prefixes":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_prefixes: %w", lineNo, err)
			}
			t.EnvPrefixes = v
		case "env_names":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_names: %w", lineNo, err)
			}
			t.EnvNames = v
		case "env_set":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_set: %w", lineNo, err)
			}
			for _, kv := range v {
				if !validEnvAssignment(kv) {
					return reg, fmt.Errorf("line %d env_set: invalid NAME=VALUE %q", lineNo, kv)
				}
			}
			t.EnvSet = v
		case "project_markers":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d project_markers: %w", lineNo, err)
			}
			t.ProjectMarkers = v
		case "state_group":
			v, err := parseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d state_group: %w", lineNo, err)
			}
			t.StateGroup = strings.ToLower(v)
		case "project_volumes":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d project_volumes: %w", lineNo, err)
			}
			t.ProjectVolumes = v
		case "shared_volumes":
			v, err := parseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d shared_volumes: %w", lineNo, err)
			}
			t.SharedVolumes = v
		default:
			return reg, fmt.Errorf("line %d: unsupported key %q", lineNo, key)
		}
		reg.Tools[current.Name] = t
		*current = t
	}
	if err := scanner.Err(); err != nil {
		return reg, err
	}
	if len(reg.Tools) == 0 {
		return reg, errors.New("registry contains no tools")
	}
	for name, t := range reg.Tools {
		if t.Image == "" {
			return reg, fmt.Errorf("tool %q: image is required", name)
		}
		switch t.Provider {
		case "stateless":
		case "python":
			if t.Role != "python" && t.Role != "pip" {
				return reg, fmt.Errorf("tool %q: python provider requires role = \"python\" or \"pip\"", name)
			}
		case "stateful":
			if t.StateGroup == "" {
				return reg, fmt.Errorf("tool %q: stateful provider requires state_group", name)
			}
			if len(t.ProjectVolumes) == 0 && len(t.SharedVolumes) == 0 {
				return reg, fmt.Errorf("tool %q: stateful provider requires at least one volume", name)
			}
			for _, spec := range append(append([]string{}, t.ProjectVolumes...), t.SharedVolumes...) {
				if _, _, err := parseVolumeBinding(spec); err != nil {
					return reg, fmt.Errorf("tool %q volume %q: %w", name, spec, err)
				}
			}
		default:
			return reg, fmt.Errorf("tool %q: unsupported provider %q", name, t.Provider)
		}
	}
	return reg, nil
}

func stripComment(s string) string {
	inQuote := false
	escaped := false
	for i, r := range s {
		if escaped {
			escaped = false
			continue
		}
		if r == '\\' && inQuote {
			escaped = true
			continue
		}
		if r == '"' {
			inQuote = !inQuote
			continue
		}
		if r == '#' && !inQuote {
			return s[:i]
		}
	}
	return s
}

func parseQuoted(s string) (string, error) {
	s = strings.TrimSpace(s)
	if len(s) < 2 || s[0] != '"' || s[len(s)-1] != '"' {
		return "", errors.New("expected quoted string")
	}
	v, err := strconv.Unquote(s)
	if err != nil {
		return "", err
	}
	return v, nil
}

func parseBool(s string) (bool, error) {
	switch strings.TrimSpace(s) {
	case "true":
		return true, nil
	case "false":
		return false, nil
	default:
		return false, errors.New("expected true or false")
	}
}

func parseStringArray(s string) ([]string, error) {
	s = strings.TrimSpace(s)
	if s == "[]" {
		return nil, nil
	}
	if len(s) < 2 || s[0] != '[' || s[len(s)-1] != ']' {
		return nil, errors.New("expected array of quoted strings")
	}
	inner := strings.TrimSpace(s[1 : len(s)-1])
	var out []string
	for len(inner) > 0 {
		inner = strings.TrimSpace(inner)
		if !strings.HasPrefix(inner, "\"") {
			return nil, errors.New("array elements must be quoted strings")
		}
		end := -1
		escaped := false
		for i := 1; i < len(inner); i++ {
			if escaped {
				escaped = false
				continue
			}
			if inner[i] == '\\' {
				escaped = true
				continue
			}
			if inner[i] == '"' {
				end = i
				break
			}
		}
		if end < 0 {
			return nil, errors.New("unterminated string")
		}
		v, err := strconv.Unquote(inner[:end+1])
		if err != nil {
			return nil, err
		}
		out = append(out, v)
		inner = strings.TrimSpace(inner[end+1:])
		if inner == "" {
			break
		}
		if inner[0] != ',' {
			return nil, errors.New("expected comma between array elements")
		}
		inner = inner[1:]
	}
	return out, nil
}

func validToolName(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			continue
		}
		return false
	}
	return true
}

// reservedToolName rejects names whose NAME.exe shim would collide with the
// cb binary itself, or which are Windows reserved device names (creating
// con.exe / nul.exe etc. misbehaves across Windows tooling).
func reservedToolName(s string) bool {
	switch s {
	case "cb", "container-bin", "con", "prn", "aux", "nul":
		return true
	}
	// main() treats any argv[0] starting with "cb-v" as the management CLI
	// (versioned binary names), so such a shim could never dispatch to a tool.
	if strings.HasPrefix(s, "cb-v") {
		return true
	}
	if len(s) == 4 && (strings.HasPrefix(s, "com") || strings.HasPrefix(s, "lpt")) && s[3] >= '1' && s[3] <= '9' {
		return true
	}
	return false
}

func listTools(reg Registry, cfgPath string) {
	names := make([]string, 0, len(reg.Tools))
	for n := range reg.Tools {
		names = append(names, n)
	}
	sort.Strings(names)
	fmt.Printf("registry: %s\nschema:   %d\n\n", cfgPath, reg.SchemaVersion)
	for _, n := range names {
		t := reg.Tools[n]
		detail := t.Provider
		if t.Role != "" {
			detail += "/" + t.Role
		}
		fmt.Printf("%-10s  %-32s  %s\n", t.Name, t.Image, detail)
	}
}

func dockerOSTypeVerdict(raw string) (status, message string) {
	normalized := strings.Join(strings.Fields(raw), " ")
	switch strings.ToLower(normalized) {
	case "linux":
		return "ok", "docker is in Linux-container mode"
	case "windows":
		return "fail", "docker is in Windows-container mode; ContainerBin runs Linux images only — switch to Linux containers from the Docker Desktop tray menu"
	default:
		if normalized == "" {
			return "warn", "container mode could not be determined"
		}
		return "warn", "unrecognized container mode: " + normalized
	}
}

func doctor(reg Registry, cfgPath string) error {
	failures := 0
	warnings := 0
	ok := func(format string, args ...any) { fmt.Printf("OK       "+format+"\n", args...) }
	warn := func(format string, args ...any) { warnings++; fmt.Printf("WARN     "+format+"\n", args...) }
	fail := func(format string, args ...any) { failures++; fmt.Printf("FAIL     "+format+"\n", args...) }

	dockerPath, err := exec.LookPath("docker")
	if err != nil {
		fail("Docker CLI not found in PATH")
	} else {
		ok("Docker CLI: %s", dockerPath)
		cmd := exec.Command("docker", "version", "--format", "{{.Server.Version}}")
		out, err := cmd.Output()
		if err != nil {
			fail("Docker engine unreachable: %v", err)
		} else {
			ok("Docker engine: %s", strings.TrimSpace(string(out)))
			cmd = exec.Command("docker", "info", "--format", "{{.OSType}}")
			out, err = cmd.Output()
			if err != nil {
				warn("docker info failed: %v", err)
			} else {
				status, msg := dockerOSTypeVerdict(string(out))
				switch status {
				case "ok":
					ok("%s", msg)
				case "warn":
					warn("%s", msg)
				case "fail":
					fail("%s", msg)
				}
			}
		}
	}

	if reg.SchemaVersion != 1 {
		fail("registry schema=%d (supported=1)", reg.SchemaVersion)
	} else {
		ok("registry schema 1: %s", cfgPath)
	}

	lf, lockPath, err := loadLockFileForRegistry()
	if err != nil {
		fail("lockfile invalid: %v", err)
	} else if lf == nil {
		warn("lockfile missing: %s (runtime is UNLOCKED)", lockPath)
	} else {
		missing := 0
		for _, image := range configuredImages(reg) {
			e, found := lf.Images[image]
			if !found {
				missing++
				continue
			}
			if exec.Command("docker", "image", "inspect", e.Resolved).Run() != nil {
				missing++
			}
		}
		if missing == 0 {
			ok("lockfile complete and exact images local: %s", lockPath)
		} else {
			fail("lockfile has %d missing/unavailable image(s); run `cb lock --check`", missing)
		}
	}

	exe, _ := os.Executable()
	exe, _ = filepath.Abs(exe)
	dir := filepath.Dir(exe)
	pathParts := filepath.SplitList(os.Getenv("PATH"))
	inPath := false
	for _, part := range pathParts {
		if strings.EqualFold(strings.TrimRight(part, `\\/`), strings.TrimRight(dir, `\\/`)) {
			inPath = true
			break
		}
	}
	if inPath {
		ok("shim directory is in PATH: %s", dir)
	} else {
		fail("shim directory is not in PATH: %s", dir)
	}

	shimProblems := 0
	for name := range reg.Tools {
		shim := filepath.Join(dir, name+".exe")
		a, e1 := os.Stat(exe)
		b, e2 := os.Stat(shim)
		if e1 != nil || e2 != nil {
			shimProblems++
			continue
		}
		if !os.SameFile(a, b) {
			warn("shim %s is a copy, not a hardlink", name)
		}
	}
	if shimProblems == 0 {
		ok("all %d registry shims exist", len(reg.Tools))
	} else {
		fail("%d registry shim(s) missing; run `cb install`", shimProblems)
	}

	if runtime.GOOS == "windows" {
		out, _ := exec.Command("where.exe", "python").Output()
		// where.exe prints one full path per line; paths may contain spaces,
		// so this must split on newlines, never on whitespace.
		var lines []string
		for _, l := range strings.Split(strings.ReplaceAll(string(out), "\r", ""), "\n") {
			if l = strings.TrimSpace(l); l != "" {
				lines = append(lines, l)
			}
		}
		if len(lines) > 0 && strings.EqualFold(filepath.Clean(lines[0]), filepath.Join(dir, "python.exe")) {
			ok("python resolves to container-bin first")
		} else {
			warn("python does not resolve to container-bin first: %s", strings.TrimSpace(string(out)))
		}
		// Scan every result: the alias warning matters most when the
		// WindowsApps stub is the FIRST match (i.e. it wins over the shim).
		for _, line := range lines {
			if strings.Contains(strings.ToLower(line), `microsoft\windowsapps\python`) {
				warn("Windows App Execution Alias for python is present on PATH; disable it in Windows Settings > Apps > App execution aliases")
				break
			}
		}
	}

	managed, err := labeledManagedVolumes()
	if err != nil {
		warn("managed volume inspection failed: %v", err)
	} else {
		ok("managed labeled volumes inspectable: %d", len(managed))
	}

	fmt.Printf("\nDoctor summary: %d failure(s), %d warning(s)\n", failures, warnings)
	if failures > 0 {
		return fmt.Errorf("%d critical check(s) failed", failures)
	}
	return nil
}

func setupCommand(cfgPath string) error {
	if err := ensureRegistryFile(cfgPath); err != nil {
		return err
	}
	if err := appendMissingDefaultTools(cfgPath); err != nil {
		return err
	}
	reg, _, err := loadRegistry()
	if err != nil {
		return err
	}
	if err := installShims(reg); err != nil {
		return err
	}
	fmt.Println("\nRunning doctor after setup...")
	return doctor(reg, cfgPath)
}

func installShims(reg Registry) error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}
	exe, err = filepath.Abs(exe)
	if err != nil {
		return err
	}
	dir := filepath.Dir(exe)
	names := make([]string, 0, len(reg.Tools))
	for name := range reg.Tools {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		dst := filepath.Join(dir, name+".exe")
		_ = os.Remove(dst)
		if err := os.Link(exe, dst); err != nil {
			if err := copyFile(exe, dst); err != nil {
				return fmt.Errorf("create %s: hardlink failed and copy fallback failed: %w", dst, err)
			}
			fmt.Printf("installed %-10s (copy fallback) -> %s\n", name, dst)
		} else {
			fmt.Printf("installed %-10s (hardlink)      -> %s\n", name, dst)
		}
	}
	fmt.Printf("\nRegistry:\n  %s\n\nAdd this directory near the front of PATH:\n  %s\n", filepath.Join(dir, "container-bin.toml"), dir)
	return nil
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	if err != nil {
		return err
	}
	_, cpErr := io.Copy(out, in)
	closeErr := out.Close()
	if cpErr != nil {
		return cpErr
	}
	return closeErr
}

// interactiveTerminal is intentionally conservative: Docker gets a TTY only
// when both stdin and stdout are character devices. Pipes/redirection and
// process-captured output remain plain -i, preserving automation semantics.
func interactiveTerminal() bool {
	in, err := os.Stdin.Stat()
	if err != nil || in.Mode()&os.ModeCharDevice == 0 {
		return false
	}
	out, err := os.Stdout.Stat()
	return err == nil && out.Mode()&os.ModeCharDevice != 0
}

func runTool(t Tool, userArgs []string) (int, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return 1, err
	}
	cwd, err = canonicalPath(cwd)
	if err != nil {
		return 1, err
	}
	root, found := findProjectRoot(cwd, projectMarkersFor(t))
	if !found {
		root = cwd
	}
	rel, err := filepath.Rel(root, cwd)
	if err != nil {
		return 1, err
	}
	workspaceRoot := workspaceRootFor(t, root)
	containerWD := workspaceRoot
	if rel != "." {
		containerWD += "/" + filepath.ToSlash(rel)
	}

	mappedUserArgs, pathMounts, err := mapToolArgs(t, root, cwd, workspaceRoot, userArgs)
	if err != nil {
		return 1, err
	}
	imageRef, err := runtimeImageForTool(t)
	if err != nil {
		return 1, err
	}
	args := []string{"run", "--rm", "-i"}
	if interactiveTerminal() {
		args = append(args, "-t")
	}
	args = append(args, "--workdir", containerWD)
	rootSpec, err := mountSpec("bind", root, workspaceRoot)
	if err != nil {
		return 1, err
	}
	args = append(args, "--mount", rootSpec)
	for _, m := range pathMounts {
		mount, err := mountSpec("bind", m.Source, m.Target)
		if err != nil {
			return 1, err
		}
		args = append(args, "--mount", mount)
	}
	for _, name := range selectedHostEnv(t) {
		args = append(args, "-e", name)
	}
	for _, kv := range t.EnvSet {
		args = append(args, "-e", kv)
	}

	switch t.Provider {
	case "python":
		envID := pythonEnvID(root, found)
		pyLabels := map[string]string{"cb.managed": "true", "cb.owner": "python313/venv"}
		if found {
			pyLabels["cb.kind"] = "project"
			pyLabels["cb.project_path"] = root
			pyLabels["cb.project_hash"] = volumeHash(root)
		} else {
			pyLabels["cb.kind"] = "compat"
		}
		venvSpec, err := mountSpec("volume", envID, "/venv")
		if err != nil {
			return 1, err
		}
		pipCacheSpec, err := mountSpec("volume", "cb-pip-cache", "/root/.cache/pip")
		if err != nil {
			return 1, err
		}
		if err := ensureManagedVolume(envID, pyLabels); err != nil {
			return 1, err
		}
		if err := ensureManagedVolume("cb-pip-cache", map[string]string{"cb.managed": "true", "cb.kind": "shared", "cb.owner": "python313/pip-cache"}); err != nil {
			return 1, err
		}
		args = append(args,
			"--mount", venvSpec,
			"--mount", pipCacheSpec,
			"-e", "VIRTUAL_ENV=/venv",
			"-e", "PATH=/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin",
		)
		args = append(args, imageRef)
		bootstrap := `if [ ! -x /venv/bin/python ]; then python -m venv /venv || exit $?; fi; if [ "$1" = "__CB_PIP__" ]; then shift; exec /venv/bin/python -m pip "$@"; else exec /venv/bin/python "$@"; fi`
		args = append(args, "sh", "-c", bootstrap, "cb")
		if t.Role == "pip" {
			args = append(args, "__CB_PIP__")
		}
		args = append(args, t.ArgsPrefix...)
		args = append(args, mappedUserArgs...)
	case "stateful":
		for _, spec := range t.ProjectVolumes {
			name, dst, err := parseVolumeBinding(spec)
			if err != nil {
				return 1, err
			}
			vol := statefulProjectVolumeID(t.StateGroup, name, root, found)
			dst = statefulWorkspaceDestination(dst, workspaceRoot)
			volSpec, err := mountSpec("volume", vol, dst)
			if err != nil {
				return 1, err
			}
			if err := ensureManagedVolume(vol, map[string]string{"cb.managed": "true", "cb.kind": "project", "cb.owner": t.StateGroup + "/" + name, "cb.project_path": root, "cb.project_hash": volumeHash(root)}); err != nil {
				return 1, err
			}
			args = append(args, "--mount", volSpec)
		}
		for _, spec := range t.SharedVolumes {
			name, dst, err := parseVolumeBinding(spec)
			if err != nil {
				return 1, err
			}
			vol := statefulSharedVolumeID(t.StateGroup, name)
			volSpec, err := mountSpec("volume", vol, dst)
			if err != nil {
				return 1, err
			}
			if err := ensureManagedVolume(vol, map[string]string{"cb.managed": "true", "cb.kind": "shared", "cb.owner": t.StateGroup + "/" + name}); err != nil {
				return 1, err
			}
			args = append(args, "--mount", volSpec)
		}
		args = append(args, imageRef)
		args = append(args, t.Command...)
		args = append(args, t.ArgsPrefix...)
		args = append(args, mappedUserArgs...)
	case "stateless":
		args = append(args, imageRef)
		args = append(args, t.Command...)
		args = append(args, t.ArgsPrefix...)
		args = append(args, mappedUserArgs...)
	default:
		return 1, fmt.Errorf("unsupported provider %q", t.Provider)
	}

	cmd := exec.Command("docker", args...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr, cmd.Env = os.Stdin, os.Stdout, os.Stderr, os.Environ()
	err = cmd.Run()
	if err == nil {
		return 0, nil
	}
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		return exitErr.ExitCode(), nil
	}
	return 1, err
}

type PathMount struct{ Source, Target string }

type pathMapper struct {
	root          string
	cwd           string
	workspaceRoot string
	mounts        []PathMount
	mountBySource map[string]string
}

// normalizeToolArgs repairs shell-level argv shapes that are unambiguous from
// the tool registry. In particular, PowerShell can hand native processes
// `-opt=` and its value as two argv elements. For path_equals options we join
// those back before path mapping, preserving the target tool's required syntax.
func normalizeToolArgs(t Tool, args []string) []string {
	out := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		arg := args[i]
		joined := false
		for _, opt := range t.PathEquals {
			prefix := opt + "="
			if arg == prefix && i+1 < len(args) {
				out = append(out, prefix+args[i+1])
				i++
				joined = true
				break
			}
		}
		if !joined {
			out = append(out, arg)
		}
	}
	return out
}

func traceTool(reg Registry, args []string) error {
	if len(args) == 0 {
		return errors.New("usage: cb trace TOOL [ARGS...]")
	}
	name := strings.ToLower(args[0])
	t, ok := reg.Tools[name]
	if !ok {
		return fmt.Errorf("no tool profile for %q", name)
	}
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}
	cwd, err = canonicalPath(cwd)
	if err != nil {
		return err
	}
	root, found := findProjectRoot(cwd, projectMarkersFor(t))
	if !found {
		root = cwd
	}
	raw := append([]string(nil), args[1:]...)
	normalized := normalizeToolArgs(t, raw)
	workspaceRoot := workspaceRootFor(t, root)
	mapped, mounts, err := mapToolArgs(t, root, cwd, workspaceRoot, raw)
	if err != nil {
		return err
	}
	fmt.Printf("tool:       %s\n", t.Name)
	fmt.Printf("image:      %s\n", t.Image)
	fmt.Printf("provider:   %s\n", t.Provider)
	fmt.Printf("cwd:        %s\n", cwd)
	fmt.Printf("root:       %s\n", root)
	fmt.Printf("workspace:  %s\n", workspaceRoot)
	fmt.Printf("raw:        %#v\n", raw)
	fmt.Printf("normalized: %#v\n", normalized)
	fmt.Printf("mapped:     %#v\n", mapped)
	if len(mounts) == 0 {
		fmt.Printf("mounts:     (none beyond %s)\n", workspaceRoot)
	} else {
		fmt.Printf("mounts:     %#v\n", mounts)
	}
	fmt.Printf("path_equals: %#v\n", t.PathEquals)
	if t.Provider == "stateful" {
		fmt.Printf("state_group: %s\n", t.StateGroup)
		for _, spec := range t.ProjectVolumes {
			name, dst, _ := parseVolumeBinding(spec)
			dst = statefulWorkspaceDestination(dst, workspaceRoot)
			fmt.Printf("project_volume: %s -> %s\n", statefulProjectVolumeID(t.StateGroup, name, root, found), dst)
		}
		for _, spec := range t.SharedVolumes {
			name, dst, _ := parseVolumeBinding(spec)
			fmt.Printf("shared_volume:  %s -> %s\n", statefulSharedVolumeID(t.StateGroup, name), dst)
		}
	}
	return nil
}

func mapToolArgs(t Tool, root, cwd, workspaceRoot string, userArgs []string) ([]string, []PathMount, error) {
	normalized := normalizeToolArgs(t, userArgs)
	if runtime.GOOS != "windows" {
		return append([]string(nil), normalized...), nil, nil
	}
	pm := &pathMapper{root: root, cwd: cwd, workspaceRoot: workspaceRoot, mountBySource: map[string]string{}}
	mapped := append([]string(nil), normalized...)
	forceNext := false
	for i, arg := range normalized {
		if forceNext {
			v, err := pm.mapArg(arg, true)
			if err != nil {
				return nil, nil, err
			}
			mapped[i] = v
			forceNext = false
			continue
		}

		if containsString(t.PathNext, arg) {
			mapped[i] = arg
			forceNext = true
			continue
		}

		eqMapped := false
		for _, opt := range t.PathEquals {
			prefix := opt + "="
			if strings.HasPrefix(arg, prefix) {
				v, err := pm.mapArg(strings.TrimPrefix(arg, prefix), true)
				if err != nil {
					return nil, nil, err
				}
				mapped[i] = prefix + v
				eqMapped = true
				break
			}
		}
		if eqMapped {
			continue
		}

		lastEnabled := t.PathLast && (len(t.PathLastIfAny) == 0 || anyArgPresent(normalized, t.PathLastIfAny))
		forceLast := lastEnabled && i == len(normalized)-1 && arg != "-" && !strings.HasPrefix(arg, "-")
		v, err := pm.mapArg(arg, forceLast)
		if err != nil {
			return nil, nil, err
		}
		mapped[i] = v
	}
	if forceNext {
		return nil, nil, fmt.Errorf("tool %q: option %q requires a path argument", t.Name, normalized[len(normalized)-1])
	}
	return mapped, pm.mounts, nil
}

func (pm *pathMapper) mapArg(arg string, force bool) (string, error) {
	hostPath, isPath, err := resolveWindowsPathArgMode(pm.cwd, arg, force)
	if err != nil {
		return "", err
	}
	if !isPath {
		return arg, nil
	}
	if rel, ok := pathWithin(pm.root, hostPath); ok {
		if rel == "." {
			return pm.workspaceRoot, nil
		}
		return pm.workspaceRoot + "/" + filepath.ToSlash(rel), nil
	}
	mountRoot, err := externalMountRoot(hostPath)
	if err != nil {
		return "", fmt.Errorf("map argument path %q: %w", arg, err)
	}
	key := strings.ToLower(filepath.Clean(mountRoot))
	target, exists := pm.mountBySource[key]
	if !exists {
		target = fmt.Sprintf("/cb/mounts/%d", len(pm.mounts))
		pm.mountBySource[key] = target
		pm.mounts = append(pm.mounts, PathMount{mountRoot, target})
	}
	rel, err := filepath.Rel(mountRoot, hostPath)
	if err != nil {
		return "", err
	}
	if rel == "." {
		return target, nil
	}
	return target + "/" + filepath.ToSlash(rel), nil
}

func containsString(xs []string, s string) bool {
	for _, x := range xs {
		if x == s {
			return true
		}
	}
	return false
}

func anyArgPresent(args, needles []string) bool {
	for _, arg := range args {
		if containsString(needles, arg) {
			return true
		}
	}
	return false
}

func validEnvAssignment(s string) bool {
	i := strings.IndexByte(s, '=')
	if i <= 0 {
		return false
	}
	name := s[:i]
	for j, r := range name {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || r == '_' || (j > 0 && r >= '0' && r <= '9') {
			continue
		}
		return false
	}
	return true
}

func selectedHostEnv(t Tool) []string {
	if len(t.EnvNames) == 0 && len(t.EnvPrefixes) == 0 {
		return nil
	}
	exact := map[string]bool{}
	for _, n := range t.EnvNames {
		exact[strings.ToUpper(n)] = true
	}
	seen := map[string]bool{}
	var out []string
	for _, kv := range os.Environ() {
		name := strings.SplitN(kv, "=", 2)[0]
		upper := strings.ToUpper(name)
		match := exact[upper]
		if !match {
			for _, p := range t.EnvPrefixes {
				if strings.HasPrefix(upper, strings.ToUpper(p)) {
					match = true
					break
				}
			}
		}
		if match && !seen[upper] {
			seen[upper] = true
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out
}

// resolveWindowsPathArg recognizes the forms that can be mapped safely without
// knowing tool-specific argument grammar:
//
//	C:\foo\bar      absolute Windows path
//	.\foo / ..\foo explicit relative Windows path
//	subdir\foo      only when it already exists on the host
//
// Plain strings that merely contain backslashes are left untouched.
func resolveWindowsPathArg(cwd, arg string) (string, bool, error) {
	return resolveWindowsPathArgMode(cwd, arg, false)
}

func resolveWindowsPathArgMode(cwd, arg string, force bool) (string, bool, error) {
	if isWindowsAbsPath(arg) {
		p, err := canonicalPath(arg)
		if err != nil {
			return "", false, fmt.Errorf("canonicalize argument path %q: %w", arg, err)
		}
		return p, true, nil
	}
	if isExplicitWindowsRelPath(arg) || (force && !strings.HasPrefix(arg, "-") && arg != "") {
		p, err := canonicalPath(filepath.Join(cwd, arg))
		if err != nil {
			return "", false, fmt.Errorf("canonicalize relative argument path %q: %w", arg, err)
		}
		return p, true, nil
	}
	if strings.Contains(arg, `\`) && !strings.ContainsAny(arg, "\r\n\t") {
		candidate := filepath.Join(cwd, arg)
		if _, err := os.Stat(candidate); err == nil {
			p, err := canonicalPath(candidate)
			if err != nil {
				return "", false, err
			}
			return p, true, nil
		}
	}
	return "", false, nil
}
func isExplicitWindowsRelPath(s string) bool {
	return strings.HasPrefix(s, `.\`) || strings.HasPrefix(s, `..\`) ||
		strings.HasPrefix(s, "./") || strings.HasPrefix(s, "../")
}

func isWindowsAbsPath(s string) bool {
	if len(s) < 3 {
		return false
	}
	c := s[0]
	isLetter := (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')
	return isLetter && s[1] == ':' && (s[2] == '\\' || s[2] == '/')
}

func pathWithin(root, p string) (string, bool) {
	rel, err := filepath.Rel(root, p)
	if err != nil {
		return "", false
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || filepath.IsAbs(rel) {
		return "", false
	}
	return rel, true
}

func externalMountRoot(hostPath string) (string, error) {
	if st, err := os.Stat(hostPath); err == nil {
		if st.IsDir() {
			return hostPath, nil
		}
		return filepath.Dir(hostPath), nil
	} else if !os.IsNotExist(err) {
		return "", err
	}
	candidate := filepath.Dir(hostPath)
	for {
		if st, err := os.Stat(candidate); err == nil {
			if !st.IsDir() {
				return "", fmt.Errorf("nearest existing ancestor is not a directory: %s", candidate)
			}
			return candidate, nil
		} else if !os.IsNotExist(err) {
			return "", err
		}
		parent := filepath.Dir(candidate)
		if parent == candidate {
			return "", fmt.Errorf("no existing ancestor for %s", hostPath)
		}
		candidate = parent
	}
}

func mountSpec(kind, src, dst string) (string, error) {
	if strings.Contains(src, ",") {
		return "", fmt.Errorf("source path/volume contains a comma and cannot be represented safely in docker --mount syntax (values are comma-separated with no escaping): %s", src)
	}
	if strings.Contains(dst, ",") {
		return "", fmt.Errorf("destination path contains a comma and cannot be represented safely in docker --mount syntax (values are comma-separated with no escaping): %s", dst)
	}
	return fmt.Sprintf("type=%s,src=%s,dst=%s", kind, src, dst), nil
}

func workspaceRootFor(t Tool, root string) string {
	if t.Provider != "stateful" {
		return "/workspace"
	}
	base := filepath.Base(filepath.Clean(root))
	if base == "." || base == string(filepath.Separator) || base == "" {
		base = "project"
	}
	// Windows project names cannot contain '/', so this remains a single
	// container path segment while preserving the basename semantics tools
	// such as `npm init` observe.
	base = strings.ReplaceAll(base, "/", "_")
	return "/workspace/" + base
}

func statefulWorkspaceDestination(dst, workspaceRoot string) string {
	if dst == "/workspace" {
		return workspaceRoot
	}
	if strings.HasPrefix(dst, "/workspace/") {
		return workspaceRoot + strings.TrimPrefix(dst, "/workspace")
	}
	return dst
}

func projectMarkersFor(t Tool) []string {
	if len(t.ProjectMarkers) > 0 {
		return t.ProjectMarkers
	}
	// Backward compatibility for registries created before v0.6, whose
	// Python sections did not yet declare project_markers explicitly.
	if t.Provider == "python" {
		return []string{"pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"}
	}
	return []string{".git"}
}

func findProjectRoot(start string, markers []string) (string, bool) {
	dir := start
	for {
		for _, marker := range markers {
			if _, err := os.Stat(filepath.Join(dir, marker)); err == nil {
				return dir, true
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

func parseVolumeBinding(spec string) (string, string, error) {
	i := strings.Index(spec, ":/")
	if i <= 0 {
		return "", "", errors.New("expected NAME:/absolute/container/path")
	}
	name, dst := spec[:i], spec[i+1:]
	if !validToolName(name) {
		return "", "", fmt.Errorf("invalid volume name %q", name)
	}
	if !strings.HasPrefix(dst, "/") {
		return "", "", errors.New("container path must be absolute")
	}
	return name, dst, nil
}

func volumeHash(root string) string {
	sum := sha256.Sum256([]byte(strings.ToLower(filepath.Clean(root))))
	return hex.EncodeToString(sum[:])[:12]
}

func statefulProjectVolumeID(group, name, root string, project bool) string {
	_ = project // root already falls back to cwd when no marker was found
	return "cb-" + group + "-" + name + "-" + volumeHash(root)
}

func statefulSharedVolumeID(group, name string) string { return "cb-" + group + "-" + name }

func canonicalPath(p string) (string, error) {
	abs, err := filepath.Abs(p)
	if err != nil {
		return "", err
	}
	if resolved, err := filepath.EvalSymlinks(abs); err == nil {
		abs = resolved
	}
	abs = filepath.Clean(abs)
	if runtime.GOOS == "windows" {
		abs = strings.ToLower(abs)
	}
	return abs, nil
}

func pythonEnvID(root string, project bool) string {
	if !project {
		return "cb-python-313-global"
	}
	return "cb-python-313-" + volumeHash(root)
}

func showEnv(reg Registry) error {
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}
	cwd, err = canonicalPath(cwd)
	if err != nil {
		return err
	}
	pt, ok := reg.Tools["python"]
	if !ok {
		return errors.New("python tool not configured")
	}
	root, found := findProjectRoot(cwd, projectMarkersFor(pt))
	if !found {
		root = cwd
	}
	fmt.Printf("cwd:          %s\nproject:      %v\nroot:         %s\n", cwd, found, root)
	if t, ok := reg.Tools["python"]; ok {
		fmt.Printf("python image: %s\npython env:   %s\npip cache:    cb-pip-cache\n", t.Image, pythonEnvID(root, found))
	} else {
		fmt.Println("python:       not configured")
	}
	return nil
}

const (
	exitUsage       = 2
	exitCbFailure   = 120
	exitInterrupted = 130
)

// osExit is an indirection so unit tests can observe the exit code. A test
// stub that returns instead of terminating will cause fatalf to continue to
// its caller, so stubs must either panic or otherwise halt the goroutine.
var osExit = os.Exit

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "container-bin: "+format+"\n", args...)
	osExit(exitCbFailure)
}

type stateVolume struct {
	Name    string
	Kind    string
	Owner   string
	Root    string
	Current bool
}

func dockerVolumeNames() ([]string, error) {
	cmd := exec.Command("docker", "volume", "ls", "--format", "{{.Name}}")
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("docker volume ls: %w", err)
	}
	var names []string
	for _, line := range strings.Split(string(out), "\n") {
		name := strings.TrimSpace(line)
		if strings.HasPrefix(name, "cb-") {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names, nil
}

func currentProjectState(reg Registry) (map[string]stateVolume, map[string]stateVolume, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return nil, nil, err
	}
	cwd, err = canonicalPath(cwd)
	if err != nil {
		return nil, nil, err
	}
	project := map[string]stateVolume{}
	shared := map[string]stateVolume{}

	for _, t := range reg.Tools {
		switch t.Provider {
		case "stateful":
			root, found := findProjectRoot(cwd, projectMarkersFor(t))
			if !found {
				root = cwd
			}
			for _, spec := range t.ProjectVolumes {
				logical, _, err := parseVolumeBinding(spec)
				if err != nil {
					return nil, nil, err
				}
				name := statefulProjectVolumeID(t.StateGroup, logical, root, found)
				project[name] = stateVolume{Name: name, Kind: "project", Owner: t.StateGroup + "/" + logical, Root: root, Current: true}
			}
			for _, spec := range t.SharedVolumes {
				logical, _, err := parseVolumeBinding(spec)
				if err != nil {
					return nil, nil, err
				}
				name := statefulSharedVolumeID(t.StateGroup, logical)
				shared[name] = stateVolume{Name: name, Kind: "shared", Owner: t.StateGroup + "/" + logical}
			}
		case "python":
			root, found := findProjectRoot(cwd, projectMarkersFor(t))
			if found {
				name := pythonEnvID(root, true)
				project[name] = stateVolume{Name: name, Kind: "project", Owner: "python313/venv", Root: root, Current: true}
			} else {
				shared["cb-python-313-global"] = stateVolume{Name: "cb-python-313-global", Kind: "compat", Owner: "python313/global"}
			}
			shared["cb-pip-cache"] = stateVolume{Name: "cb-pip-cache", Kind: "shared", Owner: "python313/pip-cache"}
		}
	}
	return project, shared, nil
}

func showState(reg Registry) error {
	actual, err := dockerVolumeNames()
	if err != nil {
		return err
	}
	project, shared, err := currentProjectState(reg)
	if err != nil {
		return err
	}
	fmt.Printf("%-9s  %-48s  %s\n", "STATUS", "VOLUME", "OWNER")
	fmt.Printf("%-9s  %-48s  %s\n", "---------", "------------------------------------------------", "-----")
	for _, name := range actual {
		if v, ok := project[name]; ok {
			fmt.Printf("%-9s  %-48s  %s\n", "CURRENT", name, v.Owner)
			continue
		}
		if v, ok := shared[name]; ok {
			fmt.Printf("%-9s  %-48s  %s\n", strings.ToUpper(v.Kind), name, v.Owner)
			continue
		}
		labels, _ := dockerVolumeLabels(name)
		if labels["cb.managed"] == "true" {
			owner := labels["cb.owner"]
			switch labels["cb.kind"] {
			case "shared":
				fmt.Printf("%-9s  %-48s  %s\n", "SHARED", name, owner)
				continue
			case "compat":
				fmt.Printf("%-9s  %-48s  %s\n", "COMPAT", name, owner)
				continue
			case "project":
				path := labels["cb.project_path"]
				if path != "" {
					if _, e := os.Stat(path); os.IsNotExist(e) {
						fmt.Printf("%-9s  %-48s  %s (%s)\n", "ORPHAN", name, owner, path)
						continue
					}
				}
				fmt.Printf("%-9s  %-48s  %s\n", "MANAGED", name, owner)
				continue
			}
		}
		fmt.Printf("%-9s  %-48s  %s\n", "OTHER", name, "legacy/unlabeled or other project state")
	}
	if len(actual) == 0 {
		fmt.Println("(no container-bin volumes found)")
	}
	fmt.Println("\nORPHAN detection applies only to v0.8+ labeled project volumes. Legacy/unlabeled volumes are never auto-deleted.")
	return nil
}

func volumeExistsSet() (map[string]bool, error) {
	names, err := dockerVolumeNames()
	if err != nil {
		return nil, err
	}
	m := map[string]bool{}
	for _, n := range names {
		m[n] = true
	}
	return m, nil
}

func gcState(reg Registry, args []string) error {
	apply := false
	orphans := false
	filter := ""
	for _, a := range args {
		switch a {
		case "--apply":
			apply = true
		case "--dry-run":
		case "--orphans":
			orphans = true
		default:
			if strings.HasPrefix(a, "-") {
				return fmt.Errorf("unknown option %q", a)
			}
			if filter != "" {
				return errors.New("usage: cb gc [TOOL|STATE_GROUP] [--orphans] [--apply]")
			}
			filter = strings.ToLower(a)
		}
	}
	if orphans {
		vols, err := labeledManagedVolumes()
		if err != nil {
			return err
		}
		var candidates []managedVolume
		for _, v := range vols {
			if v.Labels["cb.kind"] != "project" {
				continue
			}
			path := v.Labels["cb.project_path"]
			if path == "" {
				continue
			}
			if filter != "" && filter != strings.ToLower(v.Labels["cb.owner"]) && !strings.HasPrefix(strings.ToLower(v.Labels["cb.owner"]), filter+"/") {
				continue
			}
			if _, err := os.Stat(path); os.IsNotExist(err) {
				candidates = append(candidates, v)
			}
		}
		if len(candidates) == 0 {
			fmt.Println("No labeled orphan project volumes found.")
			return nil
		}
		sort.Slice(candidates, func(i, j int) bool { return candidates[i].Name < candidates[j].Name })
		if !apply {
			fmt.Println("Dry run: labeled project volumes whose recorded host project path no longer exists:")
			for _, v := range candidates {
				fmt.Printf("  %-48s  %-24s  %s\n", v.Name, v.Labels["cb.owner"], v.Labels["cb.project_path"])
			}
			fmt.Println("\nRe-run with --orphans --apply to delete. Legacy/unlabeled volumes are never included.")
			return nil
		}
		for _, v := range candidates {
			if err := removeDockerVolume(v.Name); err != nil {
				return err
			}
		}
		return nil
	}

	cwd, err := os.Getwd()
	if err != nil {
		return err
	}
	cwd, err = canonicalPath(cwd)
	if err != nil {
		return err
	}
	candidates := map[string]string{}
	for _, t := range reg.Tools {
		if filter != "" && filter != t.Name && filter != t.StateGroup && !(filter == "python" && t.Provider == "python") {
			continue
		}
		switch t.Provider {
		case "stateful":
			root, found := findProjectRoot(cwd, projectMarkersFor(t))
			if !found {
				root = cwd
			}
			for _, spec := range t.ProjectVolumes {
				logical, _, e := parseVolumeBinding(spec)
				if e != nil {
					return e
				}
				candidates[statefulProjectVolumeID(t.StateGroup, logical, root, found)] = t.StateGroup + "/" + logical
			}
		case "python":
			root, found := findProjectRoot(cwd, projectMarkersFor(t))
			if found {
				candidates[pythonEnvID(root, true)] = "python313/venv"
			}
		}
	}
	if len(candidates) == 0 {
		return errors.New("no project-scoped state matches the current directory/filter")
	}
	exists, err := volumeExistsSet()
	if err != nil {
		return err
	}
	var names []string
	for n := range candidates {
		if exists[n] {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	if len(names) == 0 {
		fmt.Println("No matching project volumes currently exist.")
		return nil
	}
	if !apply {
		fmt.Println("Dry run: the following CURRENT project volumes would be removed:")
		for _, n := range names {
			fmt.Printf("  %-48s  %s\n", n, candidates[n])
		}
		fmt.Println("\nShared caches/global state are never included. Re-run with --apply to delete these volumes.")
		return nil
	}
	for _, n := range names {
		if err := removeDockerVolume(n); err != nil {
			return err
		}
	}
	return nil
}

func removeDockerVolume(name string) error {
	cmd := exec.Command("docker", "volume", "rm", name)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("remove %s: %w", name, err)
	}
	return nil
}

type managedVolume struct {
	Name   string
	Labels map[string]string
}

func labeledManagedVolumes() ([]managedVolume, error) {
	cmd := exec.Command("docker", "volume", "ls", "--filter", "label=cb.managed=true", "--format", "{{.Name}}")
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("docker volume ls labels: %w", err)
	}
	var result []managedVolume
	for _, line := range strings.Split(string(out), "\n") {
		name := strings.TrimSpace(line)
		if name == "" {
			continue
		}
		labels, err := dockerVolumeLabels(name)
		if err != nil {
			return nil, err
		}
		result = append(result, managedVolume{Name: name, Labels: labels})
	}
	return result, nil
}

func dockerVolumeLabels(name string) (map[string]string, error) {
	cmd := exec.Command("docker", "volume", "inspect", "--format", "{{range $k, $v := .Labels}}{{$k}}={{$v}}{{println}}{{end}}", name)
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("inspect volume %s: %w", name, err)
	}
	m := map[string]string{}
	for _, line := range strings.Split(string(out), "\n") {
		if i := strings.IndexByte(line, '='); i > 0 {
			m[line[:i]] = line[i+1:]
		}
	}
	return m, nil
}

func tomlQuote(s string) string { return strconv.Quote(s) }
func tomlArray(xs []string) string {
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = strconv.Quote(x)
	}
	return "[" + strings.Join(q, ", ") + "]"
}

func discoverNPMGlobalBins(t Tool) ([]string, error) {
	globalVol := ""
	for _, spec := range t.SharedVolumes {
		logical, _, err := parseVolumeBinding(spec)
		if err != nil {
			return nil, err
		}
		if logical == "npm-global" {
			globalVol = statefulSharedVolumeID(t.StateGroup, logical)
			break
		}
	}
	if globalVol == "" {
		return nil, errors.New("npm profile has no npm-global shared volume")
	}
	script := `if [ -d /cb/npm-global/bin ]; then for f in /cb/npm-global/bin/*; do [ -e "$f" ] || continue; basename "$f"; done; fi`
	mount, err := mountSpec("volume", globalVol, "/cb/npm-global")
	if err != nil {
		return nil, err
	}
	cmd := exec.Command("docker", "run", "--rm", "--mount", mount, t.Image, "sh", "-lc", script)
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("inspect npm global bin: %w", err)
	}
	seen := map[string]bool{}
	var bins []string
	for _, line := range strings.Split(string(out), "\n") {
		name := strings.ToLower(strings.TrimSpace(line))
		// Untrusted names discovered inside the container: skip anything that
		// is not a safe shim name or that would shadow cb / Windows devices.
		if name == "" || !validToolName(name) || reservedToolName(name) || seen[name] {
			continue
		}
		seen[name] = true
		bins = append(bins, name)
	}
	sort.Strings(bins)
	return bins, nil
}

func exposeTool(reg Registry, cfgPath string, args []string) error {
	if len(args) == 0 {
		return errors.New("usage: cb expose npm [BINARY ...]")
	}
	if strings.ToLower(args[0]) != "npm" {
		return errors.New("v0.8 supports only: cb expose npm [BINARY ...]")
	}
	npm, ok := reg.Tools["npm"]
	if !ok {
		return errors.New("npm tool is not configured")
	}
	bins, err := discoverNPMGlobalBins(npm)
	if err != nil {
		return err
	}
	requested := map[string]bool{}
	for _, a := range args[1:] {
		name := strings.ToLower(a)
		// Discovery drops reserved names silently; an explicit request for
		// one deserves a visible explanation instead of "no matching binaries".
		if reservedToolName(name) {
			fmt.Printf("skip %-16s reserved name cannot be exposed as a shim\n", name)
			continue
		}
		requested[name] = true
	}
	if len(args) > 1 && len(requested) == 0 {
		return errors.New("all requested names are reserved and cannot be exposed")
	}
	var selected []string
	for _, b := range bins {
		if len(requested) == 0 || requested[b] {
			selected = append(selected, b)
		}
	}
	if len(selected) == 0 {
		return errors.New("no matching globally installed npm binaries found; try: npm install -g <package>")
	}
	data, err := os.ReadFile(cfgPath)
	if err != nil {
		return err
	}
	var add strings.Builder
	added := 0
	for _, name := range selected {
		if _, exists := reg.Tools[name]; exists {
			fmt.Printf("skip %-16s already exists in registry\n", name)
			continue
		}
		section := fmt.Sprintf("\n# Exposed from npm global prefix by cb expose npm\n[tools.%s]\nimage = %s\nprovider = \"stateful\"\ncommand = [%s]\nstate_group = %s\nshared_volumes = %s\nenv_set = %s\nenv_prefixes = %s\nenv_names = %s\n", name, tomlQuote(npm.Image), tomlQuote("/cb/npm-global/bin/"+name), tomlQuote(npm.StateGroup), tomlArray(npm.SharedVolumes), tomlArray(npm.EnvSet), tomlArray(npm.EnvPrefixes), tomlArray(npm.EnvNames))
		add.WriteString(section)
		added++
		fmt.Printf("exposed %-16s /cb/npm-global/bin/%s\n", name, name)
	}
	if added == 0 {
		return nil
	}
	combined := append(append([]byte{}, data...), []byte(add.String())...)
	if _, err := parseRegistryTOML(string(combined)); err != nil {
		return fmt.Errorf("refusing registry update: %w", err)
	}
	if err := atomicWriteFile(cfgPath, combined, 0644); err != nil {
		return err
	}
	newReg, _, err := loadRegistry()
	if err != nil {
		return fmt.Errorf("reload registry: %w", err)
	}
	return installShims(newReg)
}

func ensureManagedVolume(name string, labels map[string]string) error {
	args := []string{"volume", "create"}
	keys := make([]string, 0, len(labels))
	for k := range labels {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		args = append(args, "--label", k+"="+labels[k])
	}
	args = append(args, name)
	cmd := exec.Command("docker", args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("ensure volume %s: %w: %s", name, err, strings.TrimSpace(string(out)))
	}
	return nil
}

func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".container-bin-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	cleanup := func() { _ = os.Remove(tmpName) }
	defer cleanup()
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, perm); err != nil {
		return err
	}
	// Windows cannot rename over an existing file reliably, so keep a tiny backup window.
	bak := path + ".bak"
	_ = os.Remove(bak)
	if _, err := os.Stat(path); err == nil {
		if err := os.Rename(path, bak); err != nil {
			return err
		}
	}
	if err := os.Rename(tmpName, path); err != nil {
		_ = os.Rename(bak, path)
		return err
	}
	_ = os.Remove(bak)
	return nil
}

func recoverFromBackup(path string, validate func(backupPath string) error) (bool, error) {
	if _, err := os.Stat(path); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, err
	}
	bak := path + ".bak"
	if _, err := os.Stat(bak); err == nil {
		if err := validate(bak); err != nil {
			return false, fmt.Errorf("%s is missing and its backup %s is unusable: %w; remove the backup to fall back to defaults, or repair it and retry", path, bak, err)
		}
		if err := os.Rename(bak, path); err != nil {
			return false, err
		}
		fmt.Fprintf(os.Stderr, "container-bin: recovered %s from %s after an interrupted write\n", path, bak)
		return true, nil
	} else if !os.IsNotExist(err) {
		return false, err
	}
	return false, nil
}

func validateRegistryBackup(bak string) error {
	b, err := os.ReadFile(bak)
	if err != nil {
		return err
	}
	if len(b) == 0 {
		return errors.New("backup is empty")
	}
	// parseRegistryTOML already rejects a tool-less registry, so this needs no
	// separate check for one; keeping the rule in a single place stops the two
	// copies from drifting apart later.
	_, err = parseRegistryTOML(string(b))
	return err
}

func inspectTool(reg Registry, args []string) error {
	if len(args) != 1 {
		return errors.New("usage: cb inspect TOOL")
	}
	name := strings.ToLower(args[0])
	t, ok := reg.Tools[name]
	if !ok {
		return fmt.Errorf("tool %q not found", name)
	}
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}
	cwd, err = canonicalPath(cwd)
	if err != nil {
		return err
	}
	root, found := findProjectRoot(cwd, projectMarkersFor(t))
	if !found {
		root = cwd
	}
	fmt.Printf("name:       %s\nimage:      %s\nprovider:   %s\n", t.Name, t.Image, t.Provider)
	lock, lockPath, lerr := loadLockFileForRegistry()
	if lerr != nil {
		fmt.Printf("lock:       ERROR (%v)\n", lerr)
	} else if lock == nil {
		fmt.Printf("lock:       UNLOCKED (%s missing)\n", lockPath)
	} else if e, ok := lock.Images[t.Image]; ok && e.Configured == t.Image {
		fmt.Printf("locked:     %s\nstatus:     LOCKED\n", e.Resolved)
	} else {
		fmt.Printf("lock:       STALE/UNLOCKED (no matching entry for configured image)\n")
	}
	if t.Role != "" {
		fmt.Printf("role:       %s\n", t.Role)
	}
	if len(t.Command) > 0 {
		fmt.Printf("command:    %#v\n", t.Command)
	}
	fmt.Printf("cwd:        %s\nroot:       %s\nworkspace:  %s\n", cwd, root, workspaceRootFor(t, root))
	if t.StateGroup != "" {
		fmt.Printf("state_group: %s\n", t.StateGroup)
	}
	for _, spec := range t.ProjectVolumes {
		logical, dst, e := parseVolumeBinding(spec)
		if e != nil {
			return e
		}
		fmt.Printf("project_volume: %s -> %s\n", statefulProjectVolumeID(t.StateGroup, logical, root, found), statefulWorkspaceDestination(dst, workspaceRootFor(t, root)))
	}
	for _, spec := range t.SharedVolumes {
		logical, dst, e := parseVolumeBinding(spec)
		if e != nil {
			return e
		}
		fmt.Printf("shared_volume:  %s -> %s\n", statefulSharedVolumeID(t.StateGroup, logical), dst)
	}
	if t.Provider == "python" {
		fmt.Printf("python_env: %s\npip_cache:  cb-pip-cache\n", pythonEnvID(root, found))
	}
	if len(t.PathEquals) > 0 {
		fmt.Printf("path_equals: %#v\n", t.PathEquals)
	}
	if len(t.PathNext) > 0 {
		fmt.Printf("path_next:   %#v\n", t.PathNext)
	}
	if len(t.EnvNames) > 0 {
		fmt.Printf("env_names:   %#v\n", t.EnvNames)
	}
	if len(t.EnvPrefixes) > 0 {
		fmt.Printf("env_prefixes:%#v\n", t.EnvPrefixes)
	}
	return nil
}

func rewriteRegistryWithoutTools(cfgPath string, remove map[string]bool) error {
	data, err := os.ReadFile(cfgPath)
	if err != nil {
		return err
	}
	lines := strings.SplitAfter(string(data), "\n")
	var out strings.Builder
	skip := false
	for _, raw := range lines {
		trim := strings.TrimSpace(strings.TrimSuffix(raw, "\n"))
		if strings.HasPrefix(trim, "[tools.") && strings.HasSuffix(trim, "]") {
			name := strings.ToLower(strings.TrimSuffix(strings.TrimPrefix(trim, "[tools."), "]"))
			skip = remove[name]
		}
		if !skip {
			out.WriteString(raw)
		}
	}
	if _, err := parseRegistryTOML(out.String()); err != nil {
		return fmt.Errorf("refusing registry rewrite: %w", err)
	}
	return atomicWriteFile(cfgPath, []byte(out.String()), 0644)
}

func removeShim(name string) error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}
	path := filepath.Join(filepath.Dir(exe), strings.ToLower(name)+".exe")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	fmt.Printf("removed shim %-16s %s\n", name, path)
	return nil
}

func unexposeTools(reg Registry, cfgPath string, args []string) error {
	if len(args) == 0 {
		return errors.New("usage: cb unexpose TOOL [TOOL...]")
	}
	remove := map[string]bool{}
	for _, a := range args {
		name := strings.ToLower(a)
		t, ok := reg.Tools[name]
		if !ok {
			return fmt.Errorf("tool %q not found", name)
		}
		if len(t.Command) != 1 || !strings.HasPrefix(t.Command[0], "/cb/npm-global/bin/") {
			return fmt.Errorf("%s is not an npm-exposed tool", name)
		}
		remove[name] = true
	}
	if err := rewriteRegistryWithoutTools(cfgPath, remove); err != nil {
		return err
	}
	for name := range remove {
		if err := removeShim(name); err != nil {
			return err
		}
	}
	return nil
}

func uninstallTools(reg Registry, cfgPath string, args []string) error {
	if len(args) == 0 {
		return errors.New("usage: cb uninstall TOOL [TOOL...]")
	}
	remove := map[string]bool{}
	builtins := defaultRegistry().Tools
	for _, a := range args {
		if strings.HasPrefix(a, "-") {
			return fmt.Errorf("unknown option %q", a)
		}
		name := strings.ToLower(a)
		if _, ok := reg.Tools[name]; !ok {
			return fmt.Errorf("tool %q not found", name)
		}
		if _, ok := builtins[name]; ok {
			return fmt.Errorf("%s is a built-in profile managed by cb install; edit the registry manually if you intentionally want to disable it", name)
		}
		remove[name] = true
	}
	if err := rewriteRegistryWithoutTools(cfgPath, remove); err != nil {
		return err
	}
	for name := range remove {
		if err := removeShim(name); err != nil {
			return err
		}
	}
	return nil
}

// --- v0.9 image locking ----------------------------------------------------

func backupCommand(cfgPath string, args []string) error {
	if len(args) > 1 {
		return errors.New("usage: cb backup [BACKUP.zip]")
	}
	dir := filepath.Dir(cfgPath)
	path := ""
	if len(args) == 1 {
		path = args[0]
	} else {
		backupDir := filepath.Join(dir, "backups")
		if err := os.MkdirAll(backupDir, 0755); err != nil {
			return err
		}
		path = filepath.Join(backupDir, "container-bin-backup-"+time.Now().Format("20060102-150405")+".zip")
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	zw := zip.NewWriter(f)
	add := func(src, name string, required bool) error {
		b, err := os.ReadFile(src)
		if errors.Is(err, os.ErrNotExist) && !required {
			return nil
		}
		if err != nil {
			return err
		}
		w, err := zw.Create(name)
		if err != nil {
			return err
		}
		_, err = w.Write(b)
		return err
	}
	if err := add(cfgPath, "container-bin.toml", true); err != nil {
		zw.Close()
		f.Close()
		return err
	}
	if err := add(lockPathForRegistry(cfgPath), "container-bin.lock", false); err != nil {
		zw.Close()
		f.Close()
		return err
	}
	meta, _ := zw.Create("backup-info.txt")
	fmt.Fprintf(meta, "container-bin %s\ncreated=%s\nsource=%s\n", version, time.Now().Format(time.RFC3339), dir)
	if err := zw.Close(); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	abs, _ := filepath.Abs(path)
	fmt.Printf("backup: %s\n", abs)
	return nil
}

func restoreCommand(cfgPath string, args []string) error {
	if len(args) < 1 || len(args) > 2 || (len(args) == 2 && args[1] != "--apply") {
		return errors.New("usage: cb restore BACKUP.zip [--apply]")
	}
	apply := len(args) == 2
	zr, err := zip.OpenReader(args[0])
	if err != nil {
		return err
	}
	defer zr.Close()
	files := map[string][]byte{}
	for _, f := range zr.File {
		if f.Name != "container-bin.toml" && f.Name != "container-bin.lock" {
			continue
		}
		r, err := f.Open()
		if err != nil {
			return err
		}
		b, err := io.ReadAll(r)
		r.Close()
		if err != nil {
			return err
		}
		files[f.Name] = b
	}
	cfg, ok := files["container-bin.toml"]
	if !ok {
		return errors.New("backup does not contain container-bin.toml")
	}
	if _, err := parseRegistryTOML(string(cfg)); err != nil {
		return fmt.Errorf("backup registry invalid: %w", err)
	}
	if lock, ok := files["container-bin.lock"]; ok {
		tmp, err := os.CreateTemp("", "cb-lock-*.tmp")
		if err != nil {
			return err
		}
		name := tmp.Name()
		tmp.Close()
		defer os.Remove(name)
		if err := os.WriteFile(name, lock, 0600); err != nil {
			return err
		}
		if _, err := loadLockFile(name); err != nil {
			return fmt.Errorf("backup lock invalid: %w", err)
		}
	}
	fmt.Printf("restore source: %s\n", args[0])
	fmt.Printf("  container-bin.toml: %d bytes\n", len(cfg))
	if b, ok := files["container-bin.lock"]; ok {
		fmt.Printf("  container-bin.lock: %d bytes\n", len(b))
	} else {
		fmt.Println("  container-bin.lock: absent")
	}
	if !apply {
		fmt.Println("\nDry run only. Re-run with --apply to restore registry/lock.")
		return nil
	}
	if err := atomicWriteFile(cfgPath, cfg, 0644); err != nil {
		return err
	}
	lockPath := lockPathForRegistry(cfgPath)
	if b, ok := files["container-bin.lock"]; ok {
		if err := atomicWriteFile(lockPath, b, 0644); err != nil {
			return err
		}
	} else {
		_ = os.Remove(lockPath)
		_ = os.Remove(lockPath + ".bak")
	}
	fmt.Println("restored registry/lock atomically; run `cb install` to reconcile shims")
	return nil
}

func ensureImageLocalForTool(t Tool) error {
	ref, err := runtimeImageForTool(t)
	if err != nil {
		return err
	}
	if err := exec.Command("docker", "image", "inspect", ref).Run(); err != nil {
		return fmt.Errorf("required image is not local: %s (run `cb lock`/`cb update` first)", ref)
	}
	return nil
}

func selfTestCommand(reg Registry) error {
	if exec.Command("docker", "version", "--format", "{{.Server.Version}}").Run() != nil {
		return errors.New("Docker engine unavailable")
	}
	for _, name := range []string{"python", "node", "jq", "terraform"} {
		if t, ok := reg.Tools[name]; ok {
			if err := ensureImageLocalForTool(t); err != nil {
				return fmt.Errorf("%s prerequisite: %w", name, err)
			}
		}
	}
	tmp, err := os.MkdirTemp("", "cb-selftest-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)
	old, _ := os.Getwd()
	defer os.Chdir(old)
	project := filepath.Join(tmp, "project")
	external := filepath.Join(tmp, "external")
	if err := os.MkdirAll(project, 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(external, 0755); err != nil {
		return err
	}
	os.WriteFile(filepath.Join(project, "package.json"), []byte(`{"name":"cb-selftest","version":"1.0.0"}`), 0644)
	os.WriteFile(filepath.Join(project, "pyproject.toml"), []byte("[project]\nname='cb-selftest'\nversion='0.0.0'\n"), 0644)
	os.WriteFile(filepath.Join(project, "data.json"), []byte(`{"ok":true}`), 0644)
	os.WriteFile(filepath.Join(external, "outside.py"), []byte("print('outside-ok')\n"), 0644)
	os.MkdirAll(filepath.Join(project, "tf"), 0755)
	os.WriteFile(filepath.Join(project, "tf", "main.tf"), []byte("terraform {}\n"), 0644)
	if err := os.Chdir(project); err != nil {
		return err
	}
	run := func(name string, args ...string) error {
		t, ok := reg.Tools[name]
		if !ok {
			return fmt.Errorf("tool %s missing", name)
		}
		code, err := runTool(t, args)
		if err != nil {
			return err
		}
		if code != 0 {
			return fmt.Errorf("%s exited %d", name, code)
		}
		fmt.Printf("PASS     %s %s\n", name, strings.Join(args, " "))
		return nil
	}
	if err := run("python", "-c", "open('/venv/.cb-selftest','w').write('ok')"); err != nil {
		return err
	}
	if err := run("python", "-c", "assert open('/venv/.cb-selftest').read()=='ok'"); err != nil {
		return err
	}
	if err := run("python", filepath.Join(external, "outside.py")); err != nil {
		return err
	}
	if err := run("node", "-e", "require('fs').mkdirSync('node_modules',{recursive:true}); require('fs').writeFileSync('node_modules/.cb-selftest','ok')"); err != nil {
		return err
	}
	if err := run("node", "-e", "if(require('fs').readFileSync('node_modules/.cb-selftest','utf8')!=='ok')process.exit(9)"); err != nil {
		return err
	}
	if err := run("jq", ".", `.\data.json`); err != nil {
		return err
	}
	if err := run("terraform", `-chdir=.\tf`, "validate"); err != nil {
		return err
	}
	root, _ := canonicalPath(project)
	_ = removeDockerVolume(pythonEnvID(root, true))
	_ = removeDockerVolume(statefulProjectVolumeID("node24", "node-modules", root, true))
	fmt.Println("\nSelf-test PASS (temporary project state cleaned)")
	return nil
}

const (
	mutationLockWait          = 5 * time.Second
	mutationLockRetryInterval = 50 * time.Millisecond
)

func mutationLockPathForRegistry(cfgPath string) string {
	return filepath.Join(filepath.Dir(cfgPath), "container-bin.mutation.lock")
}

func readMutationLockHolder(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return "unknown holder"
	}
	line := strings.TrimSpace(string(data))
	if line == "" {
		return "unknown holder"
	}
	return line
}

func acquireMutationLock(cfgPath string, wait time.Duration) (func(), error) {
	path := mutationLockPathForRegistry(cfgPath)
	start := time.Now()
	for {
		f, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0644)
		if err == nil {
			token := make([]byte, 16)
			if _, rerr := rand.Read(token); rerr != nil {
				_ = f.Close()
				_ = os.Remove(path)
				return nil, rerr
			}
			tokenHex := hex.EncodeToString(token)
			line := fmt.Sprintf("pid=%d token=%s at %s", os.Getpid(), tokenHex, time.Now().Format(time.RFC3339))
			if _, werr := f.WriteString(line); werr != nil {
				_ = f.Close()
				_ = os.Remove(path)
				return nil, werr
			}
			if cerr := f.Close(); cerr != nil {
				_ = os.Remove(path)
				return nil, cerr
			}
			var once sync.Once
			return func() {
				once.Do(func() {
					data, err := os.ReadFile(path)
					if err != nil {
						return
					}
					if strings.TrimSpace(string(data)) != line {
						return
					}
					_ = os.Remove(path)
				})
			}, nil
		}
		// Windows keeps a deleted file in a pending-delete state until every
		// handle to it closes, and reports ERROR_ACCESS_DENIED rather than
		// ERROR_FILE_EXISTS for a create during that window. A release racing
		// an acquire therefore looks like a permission failure, so treat it as
		// contention and let the timeout decide.
		if !os.IsExist(err) && !(runtime.GOOS == "windows" && os.IsPermission(err)) {
			return nil, err
		}
		if time.Since(start) >= wait {
			// A permission error with no lock file to blame is a genuinely
			// unwritable directory, not contention; report what actually failed.
			if os.IsPermission(err) {
				if _, statErr := os.Stat(path); statErr != nil {
					return nil, fmt.Errorf("create %s: %w", path, err)
				}
			}
			return nil, fmt.Errorf("another cb command is mutating the registry (holder: %s); retry, or delete %s if no cb process is running", readMutationLockHolder(path), path)
		}
		time.Sleep(mutationLockRetryInterval)
	}
}

// withMutationLock is not re-entrant; call sites must not nest another
// withMutationLock-wrapped operation while holding the lock.
func withMutationLock(cfgPath string, fn func() error) error {
	release, err := acquireMutationLock(cfgPath, mutationLockWait)
	if err != nil {
		return err
	}
	defer release()

	c := make(chan os.Signal, 1)
	done := make(chan struct{})
	signal.Notify(c, os.Interrupt)
	go func() {
		select {
		case <-c:
			release()
			osExit(exitInterrupted)
		case <-done:
		}
	}()
	defer func() {
		signal.Stop(c)
		close(done)
	}()

	return fn()
}

func lockPathForRegistry(cfgPath string) string {
	return filepath.Join(filepath.Dir(cfgPath), "container-bin.lock")
}

func loadLockFileForRegistry() (*LockFile, string, error) {
	cfgPath, err := registryPath()
	if err != nil {
		return nil, "", err
	}
	path := lockPathForRegistry(cfgPath)
	lf, err := loadLockFile(path)
	return lf, path, err
}

func loadLockFile(path string) (*LockFile, error) {
	b, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		rec, err := recoverFromBackup(path, func(bak string) error {
			_, err := loadLockFile(bak)
			return err
		})
		if err != nil {
			return nil, err
		}
		if !rec {
			return nil, nil
		}
		b, err = os.ReadFile(path)
		if err != nil {
			return nil, err
		}
	} else if err != nil {
		return nil, err
	}
	lf := &LockFile{Version: 0, Images: map[string]LockEntry{}}
	var cur *LockEntry
	var curKey string
	sc := bufio.NewScanner(strings.NewReader(string(b)))
	lineNo := 0
	flush := func() error {
		if cur == nil {
			return nil
		}
		if cur.Configured == "" || cur.Resolved == "" || cur.Digest == "" {
			return fmt.Errorf("lock entry %q is incomplete", curKey)
		}
		if curKey != lockEntryID(cur.Configured) {
			return fmt.Errorf("lock entry id %q does not match configured image %q", curKey, cur.Configured)
		}
		lf.Images[cur.Configured] = *cur
		return nil
	}
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(stripComment(sc.Text()))
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			if err := flush(); err != nil {
				return nil, err
			}
			sec := strings.TrimSpace(line[1 : len(line)-1])
			if !strings.HasPrefix(sec, "images.") {
				return nil, fmt.Errorf("line %d: unsupported lock section %q", lineNo, sec)
			}
			curKey = strings.TrimPrefix(sec, "images.")
			if curKey == "" {
				return nil, fmt.Errorf("line %d: empty image lock id", lineNo)
			}
			cur = &LockEntry{}
			continue
		}
		kv := strings.SplitN(line, "=", 2)
		if len(kv) != 2 {
			return nil, fmt.Errorf("line %d: expected key = value", lineNo)
		}
		key, val := strings.TrimSpace(kv[0]), strings.TrimSpace(kv[1])
		if cur == nil {
			if key != "lock_version" {
				return nil, fmt.Errorf("line %d: unsupported top-level key %q", lineNo, key)
			}
			v, err := strconv.Atoi(val)
			if err != nil || v != 1 {
				return nil, fmt.Errorf("line %d: unsupported lock_version %q (supported: 1)", lineNo, val)
			}
			lf.Version = v
			continue
		}
		q, err := parseQuoted(val)
		if err != nil {
			return nil, fmt.Errorf("line %d %s: %w", lineNo, key, err)
		}
		switch key {
		case "configured":
			cur.Configured = q
		case "resolved":
			cur.Resolved = q
		case "digest":
			cur.Digest = q
		default:
			return nil, fmt.Errorf("line %d: unsupported lock key %q", lineNo, key)
		}
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if err := flush(); err != nil {
		return nil, err
	}
	if lf.Version != 1 {
		return nil, errors.New("lock_version = 1 is required")
	}
	return lf, nil
}

func lockEntryID(configured string) string {
	h := sha256.Sum256([]byte(configured))
	return hex.EncodeToString(h[:6])
}

func renderLockFile(lf *LockFile) []byte {
	var b strings.Builder
	b.WriteString("# container-bin immutable image lockfile\n")
	b.WriteString("# Generated by cb lock / cb update. Do not edit by hand.\n")
	b.WriteString("lock_version = 1\n")
	keys := make([]string, 0, len(lf.Images))
	for k := range lf.Images {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, configured := range keys {
		e := lf.Images[configured]
		b.WriteString("\n[images." + lockEntryID(configured) + "]\n")
		b.WriteString("configured = " + tomlQuote(e.Configured) + "\n")
		b.WriteString("resolved = " + tomlQuote(e.Resolved) + "\n")
		b.WriteString("digest = " + tomlQuote(e.Digest) + "\n")
	}
	return []byte(b.String())
}

func configuredImages(reg Registry) []string {
	set := map[string]bool{}
	for _, t := range reg.Tools {
		set[t.Image] = true
	}
	out := make([]string, 0, len(set))
	for image := range set {
		out = append(out, image)
	}
	sort.Strings(out)
	return out
}

func imageRepository(ref string) string {
	if i := strings.Index(ref, "@"); i >= 0 {
		ref = ref[:i]
	}
	lastSlash := strings.LastIndex(ref, "/")
	if colon := strings.LastIndex(ref, ":"); colon > lastSlash {
		ref = ref[:colon]
	}
	return ref
}

// canonicalRepository folds away the Docker Hub aliases that the engine
// normalizes out of RepoDigests, so that a registry entry written as
// docker.io/library/python matches the python@sha256:... digest Docker
// reports. Non-Hub registries (ghcr.io/..., private hosts) pass through.
func canonicalRepository(repo string) string {
	for _, p := range []string{"docker.io/", "index.docker.io/", "registry-1.docker.io/"} {
		if strings.HasPrefix(repo, p) {
			repo = strings.TrimPrefix(repo, p)
			break
		}
	}
	if strings.HasPrefix(repo, "library/") && strings.Count(repo, "/") == 1 {
		repo = strings.TrimPrefix(repo, "library/")
	}
	return repo
}

// matchRepoDigest selects the RepoDigest whose repository is the same image
// repository as the configured reference, modulo Docker Hub normalization.
// No match is an error condition handled by the caller (fail closed).
func matchRepoDigest(configured string, repoDigests []string) (string, bool) {
	want := canonicalRepository(imageRepository(configured))
	for _, rd := range repoDigests {
		i := strings.LastIndex(rd, "@")
		if i < 0 || !strings.HasPrefix(rd[i+1:], "sha256:") {
			continue
		}
		if canonicalRepository(rd[:i]) == want {
			return rd, true
		}
	}
	return "", false
}

func resolveImage(configured string, pull bool) (LockEntry, error) {
	if pull {
		cmd := exec.Command("docker", "pull", configured)
		cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
		if err := cmd.Run(); err != nil {
			return LockEntry{}, fmt.Errorf("docker pull %s: %w", configured, err)
		}
	}
	cmd := exec.Command("docker", "image", "inspect", "--format", `{{range .RepoDigests}}{{println .}}{{end}}`, configured)
	out, err := cmd.Output()
	if err != nil {
		return LockEntry{}, fmt.Errorf("inspect %s (pull it first or run cb lock): %w", configured, err)
	}
	lines := strings.Fields(string(out))
	if len(lines) == 0 {
		return LockEntry{}, fmt.Errorf("image %s has no RepoDigests; cannot lock it reproducibly", configured)
	}
	resolved, ok := matchRepoDigest(configured, lines)
	if !ok {
		// Fail closed: silently locking a digest from a different repository
		// (e.g. a locally re-tagged image) would record an identity the
		// configured reference never had.
		return LockEntry{}, fmt.Errorf("image %s has no RepoDigest for repository %q (locally tagged image?); pull it from its registry before locking", configured, imageRepository(configured))
	}
	i := strings.LastIndex(resolved, "@")
	return LockEntry{Configured: configured, Resolved: resolved, Digest: resolved[i+1:]}, nil
}

func runtimeImageForTool(t Tool) (string, error) {
	lf, path, err := loadLockFileForRegistry()
	if err != nil {
		return "", fmt.Errorf("lockfile: %w", err)
	}
	if lf == nil {
		return t.Image, nil
	}
	e, ok := lf.Images[t.Image]
	if !ok || e.Configured != t.Image {
		return "", fmt.Errorf("image %q is not locked in %s; run `cb update %s` or `cb lock`", t.Image, path, t.Name)
	}
	return e.Resolved, nil
}

func writeLockFile(path string, lf *LockFile) error {
	if lf.Version == 0 {
		lf.Version = 1
	}
	data := renderLockFile(lf)
	// Parse our own output before committing it.
	tmp := path + ".validate.tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return err
	}
	_, err := loadLockFile(tmp)
	_ = os.Remove(tmp)
	if err != nil {
		return fmt.Errorf("generated lockfile failed validation: %w", err)
	}
	return atomicWriteFile(path, data, 0644)
}

func lockCommand(reg Registry, cfgPath string, args []string) error {
	path := lockPathForRegistry(cfgPath)
	if len(args) == 1 && args[0] == "--check" {
		lf, err := loadLockFile(path)
		if err != nil {
			return err
		}
		if lf == nil {
			return fmt.Errorf("lockfile missing: %s (run `cb lock`)", path)
		}
		missing := 0
		for _, image := range configuredImages(reg) {
			e, ok := lf.Images[image]
			if !ok || e.Configured != image {
				fmt.Printf("MISSING  %s\n", image)
				missing++
				continue
			}
			cmd := exec.Command("docker", "image", "inspect", e.Resolved)
			if err := cmd.Run(); err != nil {
				fmt.Printf("ABSENT   %s -> %s\n", image, e.Resolved)
				missing++
			} else {
				fmt.Printf("OK       %s -> %s\n", image, e.Resolved)
			}
		}
		if missing > 0 {
			return fmt.Errorf("lock check failed: %d image(s) missing/unlocked", missing)
		}
		fmt.Printf("lock OK: %s\n", path)
		return nil
	}
	if len(args) != 0 {
		return errors.New("usage: cb lock [--check]")
	}
	lf := &LockFile{Version: 1, Images: map[string]LockEntry{}}
	for _, image := range configuredImages(reg) {
		fmt.Printf("locking  %s\n", image)
		e, err := resolveImage(image, true)
		if err != nil {
			return err
		}
		lf.Images[image] = e
		fmt.Printf("  -> %s\n", e.Resolved)
	}
	if err := writeLockFile(path, lf); err != nil {
		return err
	}
	fmt.Printf("\nlockfile: %s\n", path)
	return nil
}

func updateCommand(reg Registry, cfgPath string, args []string) error {
	if len(args) != 1 {
		return errors.New("usage: cb update TOOL | cb update --all")
	}
	path := lockPathForRegistry(cfgPath)
	lf, err := loadLockFile(path)
	if err != nil {
		return err
	}
	if lf == nil {
		lf = &LockFile{Version: 1, Images: map[string]LockEntry{}}
	}
	var images []string
	if args[0] == "--all" {
		images = configuredImages(reg)
	} else {
		name := strings.ToLower(args[0])
		t, ok := reg.Tools[name]
		if !ok {
			return fmt.Errorf("tool %q not found", name)
		}
		images = []string{t.Image}
	}
	seen := map[string]bool{}
	for _, image := range images {
		if seen[image] {
			continue
		}
		seen[image] = true
		old := lf.Images[image]
		fmt.Printf("updating %s\n", image)
		e, err := resolveImage(image, true)
		if err != nil {
			return err
		}
		lf.Images[image] = e
		if old.Resolved == "" {
			fmt.Printf("  new: %s\n", e.Resolved)
		} else if old.Resolved == e.Resolved {
			fmt.Printf("  unchanged: %s\n", e.Resolved)
		} else {
			fmt.Printf("  old: %s\n  new: %s\n", old.Resolved, e.Resolved)
		}
	}
	if err := writeLockFile(path, lf); err != nil {
		return err
	}
	fmt.Printf("lockfile: %s\n", path)
	return nil
}
