// Package lockfile owns container-bin.lock: the immutable image digest
// lockfile that pins every configured image reference to a resolved
// repository@sha256 form, plus the digest resolution that produces it.
package lockfile

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/AviBackToBlack/container-bin/internal/atomicio"
	"github.com/AviBackToBlack/container-bin/internal/registry"
	"github.com/AviBackToBlack/container-bin/internal/toml"
)

type LockEntry struct {
	Configured string
	Resolved   string
	Digest     string
}

type LockFile struct {
	Version int
	Images  map[string]LockEntry // keyed by configured image reference
}

func PathFor(cfgPath string) string {
	return filepath.Join(filepath.Dir(cfgPath), "container-bin.lock")
}

func LoadForRegistry() (*LockFile, string, error) {
	cfgPath, err := registry.Path()
	if err != nil {
		return nil, "", err
	}
	path := PathFor(cfgPath)
	lf, err := Load(path)
	return lf, path, err
}

func Load(path string) (*LockFile, error) {
	b, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		rec, err := atomicio.RecoverFromBackup(path, func(bak string) error {
			_, err := Load(bak)
			return err
		})
		if err != nil {
			return nil, err
		}
		if !rec {
			return nil, nil
		}
		b, err = os.ReadFile(path)
		if err != nil {
			return nil, err
		}
	} else if err != nil {
		return nil, err
	}
	lf := &LockFile{Version: 0, Images: map[string]LockEntry{}}
	var cur *LockEntry
	var curKey string
	sc := bufio.NewScanner(strings.NewReader(string(b)))
	lineNo := 0
	flush := func() error {
		if cur == nil {
			return nil
		}
		if cur.Configured == "" || cur.Resolved == "" || cur.Digest == "" {
			return fmt.Errorf("lock entry %q is incomplete", curKey)
		}
		if curKey != entryID(cur.Configured) {
			return fmt.Errorf("lock entry id %q does not match configured image %q", curKey, cur.Configured)
		}
		lf.Images[cur.Configured] = *cur
		return nil
	}
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(toml.StripComment(sc.Text()))
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			if err := flush(); err != nil {
				return nil, err
			}
			sec := strings.TrimSpace(line[1 : len(line)-1])
			if !strings.HasPrefix(sec, "images.") {
				return nil, fmt.Errorf("line %d: unsupported lock section %q", lineNo, sec)
			}
			curKey = strings.TrimPrefix(sec, "images.")
			if curKey == "" {
				return nil, fmt.Errorf("line %d: empty image lock id", lineNo)
			}
			cur = &LockEntry{}
			continue
		}
		kv := strings.SplitN(line, "=", 2)
		if len(kv) != 2 {
			return nil, fmt.Errorf("line %d: expected key = value", lineNo)
		}
		key, val := strings.TrimSpace(kv[0]), strings.TrimSpace(kv[1])
		if cur == nil {
			if key != "lock_version" {
				return nil, fmt.Errorf("line %d: unsupported top-level key %q", lineNo, key)
			}
			v, err := strconv.Atoi(val)
			if err != nil || v != 1 {
				return nil, fmt.Errorf("line %d: unsupported lock_version %q (supported: 1)", lineNo, val)
			}
			lf.Version = v
			continue
		}
		q, err := toml.ParseQuoted(val)
		if err != nil {
			return nil, fmt.Errorf("line %d %s: %w", lineNo, key, err)
		}
		switch key {
		case "configured":
			cur.Configured = q
		case "resolved":
			cur.Resolved = q
		case "digest":
			cur.Digest = q
		default:
			return nil, fmt.Errorf("line %d: unsupported lock key %q", lineNo, key)
		}
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if err := flush(); err != nil {
		return nil, err
	}
	if lf.Version != 1 {
		return nil, errors.New("lock_version = 1 is required")
	}
	return lf, nil
}

func entryID(configured string) string {
	h := sha256.Sum256([]byte(configured))
	return hex.EncodeToString(h[:6])
}

func render(lf *LockFile) []byte {
	var b strings.Builder
	b.WriteString("# container-bin immutable image lockfile\n")
	b.WriteString("# Generated by cb lock / cb update. Do not edit by hand.\n")
	b.WriteString("lock_version = 1\n")
	keys := make([]string, 0, len(lf.Images))
	for k := range lf.Images {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, configured := range keys {
		e := lf.Images[configured]
		b.WriteString("\n[images." + entryID(configured) + "]\n")
		b.WriteString("configured = " + toml.Quote(e.Configured) + "\n")
		b.WriteString("resolved = " + toml.Quote(e.Resolved) + "\n")
		b.WriteString("digest = " + toml.Quote(e.Digest) + "\n")
	}
	return []byte(b.String())
}

func ConfiguredImages(reg registry.Registry) []string {
	set := map[string]bool{}
	for _, t := range reg.Tools {
		set[t.Image] = true
	}
	out := make([]string, 0, len(set))
	for image := range set {
		out = append(out, image)
	}
	sort.Strings(out)
	return out
}

func imageRepository(ref string) string {
	if i := strings.Index(ref, "@"); i >= 0 {
		ref = ref[:i]
	}
	lastSlash := strings.LastIndex(ref, "/")
	if colon := strings.LastIndex(ref, ":"); colon > lastSlash {
		ref = ref[:colon]
	}
	return ref
}

// canonicalRepository folds away the Docker Hub aliases that the engine
// normalizes out of RepoDigests, so that a registry entry written as
// docker.io/library/python matches the python@sha256:... digest Docker
// reports. Non-Hub registries (ghcr.io/..., private hosts) pass through.
func canonicalRepository(repo string) string {
	for _, p := range []string{"docker.io/", "index.docker.io/", "registry-1.docker.io/"} {
		if strings.HasPrefix(repo, p) {
			repo = strings.TrimPrefix(repo, p)
			break
		}
	}
	if strings.HasPrefix(repo, "library/") && strings.Count(repo, "/") == 1 {
		repo = strings.TrimPrefix(repo, "library/")
	}
	return repo
}

// matchRepoDigest selects the RepoDigest whose repository is the same image
// repository as the configured reference, modulo Docker Hub normalization.
// No match is an error condition handled by the caller (fail closed).
func matchRepoDigest(configured string, repoDigests []string) (string, bool) {
	want := canonicalRepository(imageRepository(configured))
	for _, rd := range repoDigests {
		i := strings.LastIndex(rd, "@")
		if i < 0 || !strings.HasPrefix(rd[i+1:], "sha256:") {
			continue
		}
		if canonicalRepository(rd[:i]) == want {
			return rd, true
		}
	}
	return "", false
}

func ResolveImage(configured string, pull bool) (LockEntry, error) {
	if pull {
		cmd := exec.Command("docker", "pull", configured)
		cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
		if err := cmd.Run(); err != nil {
			return LockEntry{}, fmt.Errorf("docker pull %s: %w", configured, err)
		}
	}
	cmd := exec.Command("docker", "image", "inspect", "--format", `{{range .RepoDigests}}{{println .}}{{end}}`, configured)
	out, err := cmd.Output()
	if err != nil {
		return LockEntry{}, fmt.Errorf("inspect %s (pull it first or run cb lock): %w", configured, err)
	}
	lines := strings.Fields(string(out))
	if len(lines) == 0 {
		return LockEntry{}, fmt.Errorf("image %s has no RepoDigests; cannot lock it reproducibly", configured)
	}
	resolved, ok := matchRepoDigest(configured, lines)
	if !ok {
		// Fail closed: silently locking a digest from a different repository
		// (e.g. a locally re-tagged image) would record an identity the
		// configured reference never had.
		return LockEntry{}, fmt.Errorf("image %s has no RepoDigest for repository %q (locally tagged image?); pull it from its registry before locking", configured, imageRepository(configured))
	}
	i := strings.LastIndex(resolved, "@")
	return LockEntry{Configured: configured, Resolved: resolved, Digest: resolved[i+1:]}, nil
}

func RuntimeImageForTool(t registry.Tool) (string, error) {
	lf, path, err := LoadForRegistry()
	if err != nil {
		return "", fmt.Errorf("lockfile: %w", err)
	}
	if lf == nil {
		return t.Image, nil
	}
	e, ok := lf.Images[t.Image]
	if !ok || e.Configured != t.Image {
		return "", fmt.Errorf("image %q is not locked in %s; run `cb update %s` or `cb lock`", t.Image, path, t.Name)
	}
	return e.Resolved, nil
}

func Write(path string, lf *LockFile) error {
	if lf.Version == 0 {
		lf.Version = 1
	}
	data := render(lf)
	// Parse our own output before committing it.
	tmp := path + ".validate.tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return err
	}
	_, err := Load(tmp)
	_ = os.Remove(tmp)
	if err != nil {
		return fmt.Errorf("generated lockfile failed validation: %w", err)
	}
	return atomicio.WriteFile(path, data, 0644)
}
