package cli

import (
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/AviBackToBlack/container-bin/internal/pathmap"
	"github.com/AviBackToBlack/container-bin/internal/registry"
)

// These tests cover Expose guard paths that need no Docker daemon.
// The Docker-dependent discovery path (discoverNPMGlobalBins onward) remains
// untested here because it requires a real Docker daemon and a populated
// npm-global volume.

func TestExposeRequiresSourceTool(t *testing.T) {
	reg := registry.Default()
	if err := Expose(reg, filepath.Join(t.TempDir(), "container-bin.toml"), nil); err == nil {
		t.Fatal("expected usage error for empty args")
	} else if !strings.Contains(err.Error(), "usage: cb expose TOOL") {
		t.Fatalf("unexpected error message: %v", err)
	}
}

func TestExposeRejectsUnknownSource(t *testing.T) {
	reg := registry.Default()
	if err := Expose(reg, filepath.Join(t.TempDir(), "container-bin.toml"), []string{"notarealtool"}); err == nil {
		t.Fatal("expected not-found error")
	} else if !strings.Contains(err.Error(), `tool "notarealtool" not found`) {
		t.Fatalf("unexpected error message: %v", err)
	}
}

// terraform exists in the registry but is not npm-shaped (stateless), so
// Expose must fail closed here before any docker invocation. This also pins
// that the new %q-formatted error carries the source tool's actual name rather
// than an empty string.
func TestExposeRejectsNonNpmShapedTool(t *testing.T) {
	reg := registry.Default()
	err := Expose(reg, filepath.Join(t.TempDir(), "container-bin.toml"), []string{"terraform"})
	if err == nil {
		t.Fatal("expected error for non-npm-shaped source tool")
	}
	if !strings.Contains(err.Error(), "is not a stateful npm-shaped profile") {
		t.Fatalf("unexpected error message: %v", err)
	}
	if !strings.Contains(err.Error(), `"terraform"`) {
		t.Fatalf("error message does not name the source tool: %v", err)
	}
}

// TestRenderExposedToolSection proves that the TOML section generated by
// cb expose inherits the source tool's identity (image, state_group,
// shared_volumes and environment settings), not a hardcoded npm default.
// It uses npm22 from the default registry so the parsed tool carries the
// Node 22 runtime identity.
func TestRenderExposedToolSection(t *testing.T) {
	reg := registry.Default()
	source, ok := reg.Tools["npm22"]
	if !ok {
		t.Fatal("npm22 not in default registry")
	}

	const binary = "cowsay"
	section := renderExposedToolSection("npm22", source, binary)
	parsed, err := registry.ParseTOML("schema_version = 1\n" + section)
	if err != nil {
		t.Fatalf("rendered section invalid: %v", err)
	}

	got, ok := parsed.Tools[binary]
	if !ok {
		t.Fatal("parsed registry missing exposed tool")
	}
	if got.Image != "node:22-slim" {
		t.Errorf("image = %q, want %q", got.Image, "node:22-slim")
	}
	if got.StateGroup != "node22" {
		t.Errorf("state_group = %q, want %q", got.StateGroup, "node22")
	}
	if !reflect.DeepEqual(got.SharedVolumes, source.SharedVolumes) {
		t.Errorf("shared_volumes = %v, want %v", got.SharedVolumes, source.SharedVolumes)
	}
	wantCommand := []string{"/cb/npm-global/bin/" + binary}
	if !reflect.DeepEqual(got.Command, wantCommand) {
		t.Errorf("command = %v, want %v", got.Command, wantCommand)
	}
}

// captureStdout redirects os.Stdout to a temp file for the duration of fn,
// then restores it and returns everything fn wrote. Mirrors the helper in
// internal/diag so the new inspect/trace output lines can be asserted without
// changing those functions' signatures just for tests. Safe only because
// none of this package's tests call t.Parallel() — it swaps the process-
// global os.Stdout, so a parallel test using it would interleave captures
// silently; keep every test using it serial (same precondition
// internal/diag's copy documents at its own call site).
func captureStdout(fn func() error) (string, error) {
	f, err := os.CreateTemp("", "cb-cli-test-")
	if err != nil {
		return "", err
	}
	tmpPath := f.Name()
	defer os.Remove(tmpPath)

	real := os.Stdout
	os.Stdout = f
	defer func() { os.Stdout = real }()

	_ = fn()

	if cerr := f.Close(); cerr != nil {
		return "", cerr
	}
	data, rerr := os.ReadFile(tmpPath)
	if rerr != nil {
		return "", rerr
	}
	return string(data), nil
}

func setTestHome(t *testing.T, dir string) {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Setenv("USERPROFILE", dir)
	} else {
		t.Setenv("HOME", dir)
	}
}

func TestInspectPrintsHostMountRaw(t *testing.T) {
	dir := t.TempDir()
	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)
	if err := os.WriteFile(filepath.Join(dir, ".git"), []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateless"
host_mounts = ["%USERPROFILE%\\.claude:/root/.claude:ro"]
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	out, err := captureStdout(func() error { return Inspect(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	if !strings.Contains(out, "host_mount:  %USERPROFILE%\\.claude -> /root/.claude (ro)") {
		t.Fatalf("inspect output missing raw host_mount line:\n%s", out)
	}
}

func TestTracePrintsHostMountExpanded(t *testing.T) {
	dir := t.TempDir()
	homeDir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(homeDir, ".claude"), 0755); err != nil {
		t.Fatal(err)
	}
	setTestHome(t, homeDir)

	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)
	if err := os.WriteFile(filepath.Join(dir, ".git"), []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateless"
host_mounts = ["%USERPROFILE%/.claude:/root/.claude:ro"]
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	expectedCanon, err := pathmap.CanonicalPath(homeDir + "/.claude")
	if err != nil {
		t.Fatal(err)
	}

	out, err := captureStdout(func() error { return Trace(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	want := "host_mount:  " + expectedCanon + " -> /root/.claude (ro)"
	if !strings.Contains(out, want) {
		t.Fatalf("trace output missing expanded host_mount line (want %q):\n%s", want, out)
	}
}

func TestTraceHostMountResolveErrorIsPrintedNotFatal(t *testing.T) {
	dir := t.TempDir()
	if runtime.GOOS == "windows" {
		t.Setenv("USERPROFILE", "")
	} else {
		t.Setenv("HOME", "")
	}

	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)
	if err := os.WriteFile(filepath.Join(dir, ".git"), []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateless"
host_mounts = ["%USERPROFILE%/.claude:/root/.claude:ro"]
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	out, err := captureStdout(func() error { return Trace(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	if !strings.Contains(out, "host_mount:  %USERPROFILE%/.claude -> /root/.claude (ro)") {
		t.Fatalf("trace output missing host_mount line:\n%s", out)
	}
	if !strings.Contains(out, "resolve error:") {
		t.Fatalf("trace output missing resolve error marker:\n%s", out)
	}
}

func TestTraceHostMountMissingSourceWouldFail(t *testing.T) {
	dir := t.TempDir()
	homeDir := t.TempDir()
	setTestHome(t, homeDir)

	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)
	if err := os.WriteFile(filepath.Join(dir, ".git"), []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateless"
host_mounts = ["%USERPROFILE%/does-not-exist:/root/missing:ro"]
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	out, err := captureStdout(func() error { return Trace(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	if !strings.Contains(out, "[would fail: source does not exist]") {
		t.Fatalf("trace output missing would-fail annotation:\n%s", out)
	}
}

func TestInspectDefaultOmitsCwdMode(t *testing.T) {
	dir := t.TempDir()
	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateless"
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	out, err := captureStdout(func() error { return Inspect(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	if strings.Contains(out, "cwd_mode") {
		t.Fatalf("default inspect output should not contain cwd_mode:\n%s", out)
	}
}

func TestInspectPrintsCwdModeIsolated(t *testing.T) {
	dir := t.TempDir()
	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateful"
state_group = "g"
cwd_mode = "isolated"
shared_volumes = ["cache:/root/.cache"]
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	out, err := captureStdout(func() error { return Inspect(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	if !strings.Contains(out, "cwd_mode:   isolated") {
		t.Fatalf("inspect output missing cwd_mode: isolated:\n%s", out)
	}
	if !strings.Contains(out, "workdir:    /root") {
		t.Fatalf("inspect output missing /root workdir:\n%s", out)
	}
	if !strings.Contains(out, "project_bind_mount: (none)") {
		t.Fatalf("inspect output missing no-project-mount marker:\n%s", out)
	}
	if strings.Contains(out, "\nroot:") {
		t.Fatalf("isolated inspect output should not print a project root:\n%s", out)
	}
	if strings.Contains(out, "\nworkspace:") {
		t.Fatalf("isolated inspect output should not print a workspace:\n%s", out)
	}
}

func TestTraceDefaultStillPrintsRootAndWorkspace(t *testing.T) {
	dir := t.TempDir()
	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)
	if err := os.WriteFile(filepath.Join(dir, ".git"), []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateless"
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	out, err := captureStdout(func() error { return Trace(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	if !strings.Contains(out, "\nroot:") {
		t.Fatalf("default trace output missing root line:\n%s", out)
	}
	if !strings.Contains(out, "\nworkspace:") {
		t.Fatalf("default trace output missing workspace line:\n%s", out)
	}
	if strings.Contains(out, "cwd_mode") {
		t.Fatalf("default trace output should not contain cwd_mode:\n%s", out)
	}
}

func TestTraceIsolatedNoProjectMount(t *testing.T) {
	dir := t.TempDir()
	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateful"
state_group = "g"
cwd_mode = "isolated"
shared_volumes = ["cache:/root/.cache"]
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	out, err := captureStdout(func() error { return Trace(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	if !strings.Contains(out, "cwd_mode:   isolated") {
		t.Fatalf("trace output missing cwd_mode: isolated:\n%s", out)
	}
	if !strings.Contains(out, "workdir:    /root") {
		t.Fatalf("trace output missing /root workdir:\n%s", out)
	}
	if !strings.Contains(out, "project_bind_mount: (none)") {
		t.Fatalf("trace output missing no-project-mount marker:\n%s", out)
	}
	if strings.Contains(out, "\nroot:") {
		t.Fatalf("isolated trace output should not print a project root:\n%s", out)
	}
	if strings.Contains(out, "\nworkspace:") {
		t.Fatalf("isolated trace output should not print a workspace:\n%s", out)
	}
}

func TestTraceHostMountUNCWouldFail(t *testing.T) {
	if runtime.GOOS != "windows" {
		t.Skip("UNC resolution is only meaningful on Windows")
	}
	dir := t.TempDir()
	t.Setenv("USERPROFILE", `\\server\share\home`)

	old, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)
	if err := os.WriteFile(filepath.Join(dir, ".git"), []byte{}, 0644); err != nil {
		t.Fatal(err)
	}

	reg, err := registry.ParseTOML(`[tools.demo]
image = "demo:1"
provider = "stateless"
host_mounts = ["%USERPROFILE%/.claude:/root/.claude:ro"]
`)
	if err != nil {
		t.Fatalf("parse registry: %v", err)
	}

	out, err := captureStdout(func() error { return Trace(reg, []string{"demo"}) })
	if err != nil {
		t.Fatalf("capture: %v", err)
	}
	if !strings.Contains(out, "[would fail: resolves to a UNC path, which Docker Desktop cannot share]") {
		t.Fatalf("trace output missing UNC would-fail annotation:\n%s", out)
	}
}
