package cli

import (
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/AviBackToBlack/container-bin/internal/registry"
)

// These tests cover Expose guard paths that need no Docker daemon.
// The Docker-dependent discovery path (discoverNPMGlobalBins onward) remains
// untested here because it requires a real Docker daemon and a populated
// npm-global volume.

func TestExposeRequiresSourceTool(t *testing.T) {
	reg := registry.Default()
	if err := Expose(reg, filepath.Join(t.TempDir(), "container-bin.toml"), nil); err == nil {
		t.Fatal("expected usage error for empty args")
	} else if !strings.Contains(err.Error(), "usage: cb expose TOOL") {
		t.Fatalf("unexpected error message: %v", err)
	}
}

func TestExposeRejectsUnknownSource(t *testing.T) {
	reg := registry.Default()
	if err := Expose(reg, filepath.Join(t.TempDir(), "container-bin.toml"), []string{"notarealtool"}); err == nil {
		t.Fatal("expected not-found error")
	} else if !strings.Contains(err.Error(), `tool "notarealtool" not found`) {
		t.Fatalf("unexpected error message: %v", err)
	}
}

// terraform exists in the registry but is not npm-shaped (stateless), so
// Expose must fail closed here before any docker invocation. This also pins
// that the new %q-formatted error carries the source tool's actual name rather
// than an empty string.
func TestExposeRejectsNonNpmShapedTool(t *testing.T) {
	reg := registry.Default()
	err := Expose(reg, filepath.Join(t.TempDir(), "container-bin.toml"), []string{"terraform"})
	if err == nil {
		t.Fatal("expected error for non-npm-shaped source tool")
	}
	if !strings.Contains(err.Error(), "is not a stateful npm-shaped profile") {
		t.Fatalf("unexpected error message: %v", err)
	}
	if !strings.Contains(err.Error(), `"terraform"`) {
		t.Fatalf("error message does not name the source tool: %v", err)
	}
}

// TestRenderExposedToolSection proves that the TOML section generated by
// cb expose inherits the source tool's identity (image, state_group,
// shared_volumes and environment settings), not a hardcoded npm default.
// It uses npm22 from the default registry so the parsed tool carries the
// Node 22 runtime identity.
func TestRenderExposedToolSection(t *testing.T) {
	reg := registry.Default()
	source, ok := reg.Tools["npm22"]
	if !ok {
		t.Fatal("npm22 not in default registry")
	}

	const binary = "cowsay"
	section := renderExposedToolSection("npm22", source, binary)
	parsed, err := registry.ParseTOML("schema_version = 1\n" + section)
	if err != nil {
		t.Fatalf("rendered section invalid: %v", err)
	}

	got, ok := parsed.Tools[binary]
	if !ok {
		t.Fatal("parsed registry missing exposed tool")
	}
	if got.Image != "node:22-slim" {
		t.Errorf("image = %q, want %q", got.Image, "node:22-slim")
	}
	if got.StateGroup != "node22" {
		t.Errorf("state_group = %q, want %q", got.StateGroup, "node22")
	}
	if !reflect.DeepEqual(got.SharedVolumes, source.SharedVolumes) {
		t.Errorf("shared_volumes = %v, want %v", got.SharedVolumes, source.SharedVolumes)
	}
	wantCommand := []string{"/cb/npm-global/bin/" + binary}
	if !reflect.DeepEqual(got.Command, wantCommand) {
		t.Errorf("command = %v, want %v", got.Command, wantCommand)
	}
}
