// Package registry owns the container-bin tool registry: the Tool/Registry
// types, the TOML subset parser that reads container-bin.toml, the built-in
// default profiles, and the on-disk registry lifecycle.
package registry

import (
	"bufio"
	"errors"
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/AviBackToBlack/container-bin/internal/toml"
)

// Tool is deliberately generic. Provider owns lifecycle/state semantics;
// Command is prepended inside the container. An empty Command means: use the
// image ENTRYPOINT as-is (handy for images such as ghcr.io/jqlang/jq).
type Tool struct {
	Name            string
	DefaultFamily   string // runtime family whose unversioned alias this profile can supply
	DefaultVersion  string // version label within DefaultFamily
	DefaultAlias    string // unversioned shim name supplied by this concrete profile
	Image           string
	Provider        string // stateless, python
	Role            string // provider-specific: python, pip
	Command         []string
	ArgsPrefix      []string
	PathNext        []string // options whose following argv is a path
	PathEquals      []string // options of the form --opt=PATH
	PathLast        bool     // final non-option argv is a path
	PathLastIfAny   []string // apply PathLast only when any listed argv is present
	EnvPrefixes     []string // host env var prefixes passed into the container
	EnvNames        []string // exact host env var names passed into the container
	EnvSet          []string // literal NAME=VALUE entries injected into the container
	ProjectMarkers  []string // tool/provider-specific project root markers
	ProjectRootMode string   // "nearest" (default) or "outermost" matching marker
	StateGroup      string   // stable namespace shared by related stateful tools
	ProjectVolumes  []string // NAME:CONTAINER_PATH, project-scoped named volumes
	SharedVolumes   []string // NAME:CONTAINER_PATH, shared named volumes
	HostMounts      []string // SOURCE:/CONTAINER_PATH:ro|rw, explicit host bind mounts
	CwdMode         string   // "project" or "isolated"; empty means "project"
}

type Registry struct {
	SchemaVersion int
	Tools         map[string]Tool
	Defaults      map[string]string // runtime family -> selected version
}

// MaxSchemaVersion is the newest registry schema this build can parse.
// Diagnostics and parsing must share this value so a registry accepted at
// startup is not subsequently reported as unsupported by cb doctor.
const MaxSchemaVersion = 2

const DefaultTOML = `# container-bin tool registry
schema_version = 2
# Generated by cb. Edit this file, then run: cb install
#
# provider = "stateless" => disposable container, no tool-specific state
# provider = "python"    => legacy Python provider: project /venv + shared pip cache
# provider = "stateful"  => generic declarative persistent volumes
#
# Tool-semantics rules:
# path_next   = ["-i"]       => argv immediately following this option is a host path
# path_equals = ["-chdir"]   => -chdir=HOST_PATH is rewritten safely
# path_last   = true          => final non-option argv is treated as a host path
# path_last_if_any = ["-i"]  => path_last only applies if one of these argv exists
# env_prefixes / env_names   => explicitly pass selected host environment variables
# env_set                    => literal NAME=VALUE entries injected into the container
# project_markers            => files/dirs used to find this tool's project root
# project_root_mode          => "nearest" (default) or "outermost" matching marker
# state_group                => namespace shared by related stateful shims
# project_volumes            => ["name:/container/path"] scoped by project root
# shared_volumes             => ["name:/container/path"] shared across projects
# host_mounts                => ["%USERPROFILE%\\.claude:/root/.claude:ro"] explicit host bind mounts
# cwd_mode                   => "project" (default) or "isolated" (ignore CWD, no project bind mount)
# default_family/version/alias => concrete profile backing an unversioned runtime alias

[defaults.node]
version = "24"

[tools.python]
image = "python:3.13-slim"
provider = "python"
role = "python"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.python3]
image = "python:3.13-slim"
provider = "python"
role = "python"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.pip]
image = "python:3.13-slim"
provider = "python"
role = "pip"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.pip3]
image = "python:3.13-slim"
provider = "python"
role = "pip"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.jq]
image = "ghcr.io/jqlang/jq:latest"
provider = "stateless"

[tools.yq]
image = "mikefarah/yq:latest"
provider = "stateless"
env_names = ["NO_COLOR"]

[tools.terraform]
image = "hashicorp/terraform:latest"
provider = "stateless"
path_equals = ["-chdir"]
env_prefixes = ["TF_", "AWS_", "ARM_", "AZURE_", "GOOGLE_", "GCLOUD_", "CLOUDFLARE_", "HCLOUD_", "DIGITALOCEAN_", "LINODE_", "OVH_", "VAULT_", "CONSUL_"]
env_names = ["HOME", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.ffmpeg]
image = "lscr.io/linuxserver/ffmpeg:latest"
provider = "stateless"
# Intentionally no forced path rules: FFmpeg inputs can also be URLs, pipes,
# devices and lavfi expressions. Generic host-path detection is safer.

[tools.node24]
default_family = "node"
default_version = "24"
default_alias = "node"
image = "node:24-slim"
provider = "stateful"
command = ["node"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "NPM_CONFIG_REGISTRY", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npm24]
default_family = "node"
default_version = "24"
default_alias = "npm"
image = "node:24-slim"
provider = "stateful"
command = ["npm"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npx24]
default_family = "node"
default_version = "24"
default_alias = "npx"
image = "node:24-slim"
provider = "stateful"
command = ["npx"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.node22]
default_family = "node"
default_version = "22"
default_alias = "node"
image = "node:22-slim"
provider = "stateful"
command = ["node"]
state_group = "node22"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "NPM_CONFIG_REGISTRY", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npm22]
default_family = "node"
default_version = "22"
default_alias = "npm"
image = "node:22-slim"
provider = "stateful"
command = ["npm"]
state_group = "node22"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npx22]
default_family = "node"
default_version = "22"
default_alias = "npx"
image = "node:22-slim"
provider = "stateful"
command = ["npx"]
state_group = "node22"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.go]
image = "golang:1.24"
provider = "stateful"
command = ["go"]
state_group = "go124"
project_markers = ["go.mod", "go.work", ".git"]
shared_volumes = ["gomodcache:/go/pkg/mod", "gobuild:/root/.cache/go-build", "gobin:/go/bin"]
# No path_next: everything after 'go run PKG' is handed to the user's program, so
# forcing the value after -o/-C would rewrite ordinary flags such as 'go run . -o json'
# into container paths. Real output paths are already mapped by the general rules
# (absolute and .\rel forms), and a bare name resolves against the container working
# directory, which is the project.
# Do not allowlist path-valued variables; Windows paths are meaningless inside the Linux container
env_names = ["GOFLAGS", "GOPROXY", "GONOPROXY", "GOPRIVATE", "GOSUMDB", "GONOSUMDB", "GOINSECURE", "GOOS", "GOARCH", "GOARM", "CGO_ENABLED", "GOTOOLCHAIN", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.gofmt]
image = "golang:1.24"
provider = "stateful"
command = ["gofmt"]
state_group = "go124"
project_markers = ["go.mod", "go.work", ".git"]
shared_volumes = ["gomodcache:/go/pkg/mod", "gobuild:/root/.cache/go-build", "gobin:/go/bin"]
# No path_last: a bare final argument like the value of -r is not a file, and real
# file operands are already mapped by the general path-shape rules.
# Do not allowlist path-valued variables; Windows paths are meaningless inside the Linux container
env_names = ["GOFLAGS", "GOPROXY", "GONOPROXY", "GOPRIVATE", "GOSUMDB", "GONOSUMDB", "GOINSECURE", "GOOS", "GOARCH", "GOARM", "CGO_ENABLED", "GOTOOLCHAIN", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.rustc]
image = "rust:1.98.1-slim-bookworm"
provider = "stateless"
command = ["rustc"]
project_markers = ["Cargo.toml", "rust-toolchain.toml", "rust-toolchain", ".git"]

[tools.cargo]
image = "rust:1.98.1-slim-bookworm"
provider = "stateful"
command = ["cargo"]
state_group = "rust198"
project_markers = ["Cargo.toml", "rust-toolchain.toml", "rust-toolchain", ".git"]
project_root_mode = "outermost"
shared_volumes = ["registry:/usr/local/cargo/registry", "git:/usr/local/cargo/git", "global:/cb/cargo-global"]
env_set = ["CARGO_INSTALL_ROOT=/cb/cargo-global", "PATH=/cb/cargo-global/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]
env_prefixes = ["CARGO_REGISTRIES_"]
env_names = ["CARGO_NET_OFFLINE", "CARGO_TERM_COLOR", "CARGO_HTTP_TIMEOUT", "CARGO_HTTP_MULTIPLEXING", "CARGO_HTTP_LOW_SPEED_LIMIT", "RUST_BACKTRACE", "RUST_LOG", "RUSTFLAGS", "RUSTDOCFLAGS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]
path_next = ["--target-dir", "--manifest-path"]
path_equals = ["--target-dir", "--manifest-path"]

[tools.uv]
image = "ghcr.io/astral-sh/uv:0.12-python3.13-trixie-slim"
provider = "stateful"
command = ["uv"]
state_group = "uv012-py313"
project_markers = ["pyproject.toml", "uv.lock", "requirements.txt", "setup.py", "setup.cfg", ".python-version", ".git"]
project_volumes = ["project-env:/cb/uv-project-env"]
shared_volumes = ["cache:/root/.cache/uv", "tools:/cb/uv-tools", "tool-bin:/cb/uv-bin"]
env_set = ["UV_PROJECT_ENVIRONMENT=/cb/uv-project-env", "VIRTUAL_ENV=/cb/uv-project-env", "UV_CACHE_DIR=/root/.cache/uv", "UV_TOOL_DIR=/cb/uv-tools", "UV_TOOL_BIN_DIR=/cb/uv-bin", "UV_LINK_MODE=copy", "UV_PYTHON_DOWNLOADS=never", "PATH=/cb/uv-project-env/bin:/cb/uv-bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin"]
env_prefixes = ["UV_INDEX_"]
env_names = ["UV_INDEX", "UV_DEFAULT_INDEX", "UV_EXTRA_INDEX_URL", "UV_NO_INDEX", "UV_NATIVE_TLS", "UV_OFFLINE", "UV_NO_CACHE", "UV_FROZEN", "UV_LOCKED", "UV_NO_PROGRESS", "UV_COLOR", "UV_HTTP_TIMEOUT", "UV_HTTP_RETRIES", "UV_CONCURRENT_DOWNLOADS", "UV_CONCURRENT_BUILDS", "UV_CONCURRENT_INSTALLS", "UV_INSECURE_HOST", "UV_KEYRING_PROVIDER", "UV_PRERELEASE", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]
# No forced path rules: uv has many subcommands and several pass arguments to
# child tools. Absolute and explicit relative paths still use the general mapper.

[tools.uvx]
image = "ghcr.io/astral-sh/uv:0.12-python3.13-trixie-slim"
provider = "stateful"
command = ["uvx"]
state_group = "uv012-py313"
project_markers = ["pyproject.toml", "uv.lock", "requirements.txt", "setup.py", "setup.cfg", ".python-version", ".git"]
shared_volumes = ["cache:/root/.cache/uv", "tools:/cb/uv-tools", "tool-bin:/cb/uv-bin"]
env_set = ["UV_CACHE_DIR=/root/.cache/uv", "UV_TOOL_DIR=/cb/uv-tools", "UV_TOOL_BIN_DIR=/cb/uv-bin", "UV_LINK_MODE=copy", "UV_PYTHON_DOWNLOADS=never", "PATH=/cb/uv-bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin"]
env_prefixes = ["UV_INDEX_"]
env_names = ["UV_INDEX", "UV_DEFAULT_INDEX", "UV_EXTRA_INDEX_URL", "UV_NO_INDEX", "UV_NATIVE_TLS", "UV_OFFLINE", "UV_NO_CACHE", "UV_NO_PROGRESS", "UV_COLOR", "UV_HTTP_TIMEOUT", "UV_HTTP_RETRIES", "UV_CONCURRENT_DOWNLOADS", "UV_CONCURRENT_BUILDS", "UV_CONCURRENT_INSTALLS", "UV_INSECURE_HOST", "UV_KEYRING_PROVIDER", "UV_PRERELEASE", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]
`

func Default() Registry {
	reg, err := ParseTOML(DefaultTOML)
	if err != nil {
		panic("invalid built-in registry: " + err.Error())
	}
	return reg
}

func DefaultToolSections() map[string]string {
	return defaultSections("tools.")
}

func DefaultFamilySections() map[string]string {
	return defaultSections("defaults.")
}

func defaultSections(prefix string) map[string]string {
	sections := map[string]string{}
	var current string
	var b strings.Builder
	flush := func() {
		if current != "" {
			sections[current] = "\n" + b.String()
		}
		b.Reset()
	}
	for _, line := range strings.Split(DefaultTOML, "\n") {
		trim := strings.TrimSpace(line)
		if strings.HasPrefix(trim, "[") && strings.HasSuffix(trim, "]") {
			flush()
			section := strings.TrimSuffix(strings.TrimPrefix(trim, "["), "]")
			current = ""
			if strings.HasPrefix(section, prefix) {
				current = strings.TrimPrefix(section, prefix)
			}
		}
		if current != "" {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	flush()
	return sections
}

// ParseTOML intentionally supports only the tiny TOML subset used by
// container-bin's registry: [tools.NAME], [defaults.FAMILY], quoted strings and
// arrays of quoted strings. Rejecting unknown syntax is safer than silently
// misreading config.
func ParseTOML(s string) (Registry, error) {
	reg := Registry{SchemaVersion: 1, Tools: map[string]Tool{}, Defaults: map[string]string{}}
	var currentTool, currentDefault string
	scanner := bufio.NewScanner(strings.NewReader(s))
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(toml.StripComment(scanner.Text()))
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "[") {
			if !strings.HasSuffix(line, "]") {
				return reg, fmt.Errorf("line %d: malformed section", lineNo)
			}
			sec := strings.TrimSpace(line[1 : len(line)-1])
			switch {
			case strings.HasPrefix(sec, "tools.") && len(sec) > len("tools."):
				name := strings.ToLower(strings.TrimSpace(strings.TrimPrefix(sec, "tools.")))
				if !ValidToolName(name) {
					return reg, fmt.Errorf("line %d: invalid tool name %q", lineNo, name)
				}
				if ReservedToolName(name) {
					return reg, fmt.Errorf("line %d: tool name %q is reserved (would collide with cb itself or a Windows device name); rename or delete the [tools.%s] section in the registry file to recover", lineNo, name, name)
				}
				if _, dup := reg.Tools[name]; dup {
					return reg, fmt.Errorf("line %d: duplicate [tools.%s] section", lineNo, name)
				}
				reg.Tools[name] = Tool{Name: name, Provider: "stateless"}
				currentTool, currentDefault = name, ""
			case strings.HasPrefix(sec, "defaults.") && len(sec) > len("defaults."):
				family := strings.ToLower(strings.TrimSpace(strings.TrimPrefix(sec, "defaults.")))
				if !ValidToolName(family) {
					return reg, fmt.Errorf("line %d: invalid default family %q", lineNo, family)
				}
				if _, dup := reg.Defaults[family]; dup {
					return reg, fmt.Errorf("line %d: duplicate [defaults.%s] section", lineNo, family)
				}
				reg.Defaults[family] = ""
				currentTool, currentDefault = "", family
			default:
				return reg, fmt.Errorf("line %d: only [tools.NAME] and [defaults.FAMILY] sections are supported", lineNo)
			}
			continue
		}
		if currentTool == "" && currentDefault == "" {
			kv := strings.SplitN(line, "=", 2)
			if len(kv) == 2 && strings.TrimSpace(kv[0]) == "schema_version" {
				v, err := strconv.Atoi(strings.TrimSpace(kv[1]))
				if err != nil || v < 1 {
					return reg, fmt.Errorf("line %d: invalid schema_version", lineNo)
				}
				if v > MaxSchemaVersion {
					return reg, fmt.Errorf("line %d: registry schema_version %d is newer than this cb supports (max %d)", lineNo, v, MaxSchemaVersion)
				}
				reg.SchemaVersion = v
				continue
			}
			return reg, fmt.Errorf("line %d: key outside a registry section", lineNo)
		}
		kv := strings.SplitN(line, "=", 2)
		if len(kv) != 2 {
			return reg, fmt.Errorf("line %d: expected key = value", lineNo)
		}
		key := strings.TrimSpace(kv[0])
		value := strings.TrimSpace(kv[1])
		if currentDefault != "" {
			if key != "version" {
				return reg, fmt.Errorf("line %d: unsupported key %q in [defaults.%s]", lineNo, key, currentDefault)
			}
			v, err := toml.ParseQuoted(value)
			if err != nil || !validVersion(v) {
				return reg, fmt.Errorf("line %d version: expected a non-empty lowercase version label", lineNo)
			}
			if reg.Defaults[currentDefault] != "" {
				return reg, fmt.Errorf("line %d: duplicate version in [defaults.%s]", lineNo, currentDefault)
			}
			reg.Defaults[currentDefault] = v
			continue
		}
		t := reg.Tools[currentTool]
		switch key {
		case "default_family":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d default_family: %w", lineNo, err)
			}
			t.DefaultFamily = strings.ToLower(v)
		case "default_version":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d default_version: %w", lineNo, err)
			}
			t.DefaultVersion = strings.ToLower(v)
		case "default_alias":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d default_alias: %w", lineNo, err)
			}
			t.DefaultAlias = strings.ToLower(v)
		case "image":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d image: %w", lineNo, err)
			}
			t.Image = v
		case "provider":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d provider: %w", lineNo, err)
			}
			t.Provider = strings.ToLower(v)
		case "role":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d role: %w", lineNo, err)
			}
			t.Role = strings.ToLower(v)
		case "command":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d command: %w", lineNo, err)
			}
			t.Command = v
		case "args_prefix":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d args_prefix: %w", lineNo, err)
			}
			t.ArgsPrefix = v
		case "path_next":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_next: %w", lineNo, err)
			}
			t.PathNext = v
		case "path_equals":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_equals: %w", lineNo, err)
			}
			t.PathEquals = v
		case "path_last":
			v, err := toml.ParseBool(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_last: %w", lineNo, err)
			}
			t.PathLast = v
		case "path_last_if_any":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_last_if_any: %w", lineNo, err)
			}
			t.PathLastIfAny = v
		case "env_prefixes":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_prefixes: %w", lineNo, err)
			}
			t.EnvPrefixes = v
		case "env_names":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_names: %w", lineNo, err)
			}
			t.EnvNames = v
		case "env_set":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_set: %w", lineNo, err)
			}
			for _, kv := range v {
				if !validEnvAssignment(kv) {
					return reg, fmt.Errorf("line %d env_set: invalid NAME=VALUE %q", lineNo, kv)
				}
			}
			t.EnvSet = v
		case "project_markers":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d project_markers: %w", lineNo, err)
			}
			t.ProjectMarkers = v
		case "project_root_mode":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d project_root_mode: %w", lineNo, err)
			}
			t.ProjectRootMode = strings.ToLower(v)
		case "state_group":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d state_group: %w", lineNo, err)
			}
			t.StateGroup = strings.ToLower(v)
		case "project_volumes":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d project_volumes: %w", lineNo, err)
			}
			t.ProjectVolumes = v
		case "shared_volumes":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d shared_volumes: %w", lineNo, err)
			}
			t.SharedVolumes = v
		case "host_mounts":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d host_mounts: %w", lineNo, err)
			}
			t.HostMounts = v
		case "cwd_mode":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d cwd_mode: %w", lineNo, err)
			}
			t.CwdMode = strings.ToLower(v)
		default:
			return reg, fmt.Errorf("line %d: unsupported key %q", lineNo, key)
		}
		reg.Tools[currentTool] = t
	}
	if err := scanner.Err(); err != nil {
		return reg, err
	}
	if len(reg.Tools) == 0 {
		return reg, errors.New("registry contains no tools")
	}
	for name, t := range reg.Tools {
		if t.Image == "" {
			return reg, fmt.Errorf("tool %q: image is required", name)
		}
		switch t.Provider {
		case "stateless":
		case "python":
			if t.Role != "python" && t.Role != "pip" {
				return reg, fmt.Errorf("tool %q: python provider requires role = \"python\" or \"pip\"", name)
			}
		case "stateful":
			if t.StateGroup == "" {
				return reg, fmt.Errorf("tool %q: stateful provider requires state_group", name)
			}
			if len(t.ProjectVolumes) == 0 && len(t.SharedVolumes) == 0 {
				return reg, fmt.Errorf("tool %q: stateful provider requires at least one volume", name)
			}
			for _, spec := range append(append([]string{}, t.ProjectVolumes...), t.SharedVolumes...) {
				if _, _, err := ParseVolumeBinding(spec); err != nil {
					return reg, fmt.Errorf("tool %q volume %q: %w", name, spec, err)
				}
			}
		default:
			return reg, fmt.Errorf("tool %q: unsupported provider %q", name, t.Provider)
		}
		switch t.CwdMode {
		case "", "project", "isolated":
		default:
			return reg, fmt.Errorf("tool %q: cwd_mode must be \"project\" or \"isolated\"", name)
		}
		switch t.ProjectRootMode {
		case "", "nearest", "outermost":
		default:
			return reg, fmt.Errorf("tool %q: project_root_mode must be \"nearest\" or \"outermost\"", name)
		}
		if t.CwdMode == "isolated" && len(t.ProjectVolumes) > 0 {
			return reg, fmt.Errorf("tool %q: cwd_mode = \"isolated\" cannot declare project_volumes", name)
		}
		if t.CwdMode == "isolated" && t.Provider == "python" {
			return reg, fmt.Errorf("tool %q: cwd_mode = \"isolated\" is not supported for the python provider", name)
		}
		if t.CwdMode == "isolated" && len(t.ProjectMarkers) > 0 {
			return reg, fmt.Errorf("tool %q: cwd_mode = \"isolated\" cannot declare project_markers", name)
		}
		if t.CwdMode == "isolated" && t.ProjectRootMode != "" {
			return reg, fmt.Errorf("tool %q: cwd_mode = \"isolated\" cannot declare project_root_mode", name)
		}
		if err := validateHostMounts(t); err != nil {
			return reg, fmt.Errorf("tool %q: %w", name, err)
		}
	}
	if err := validateDefaults(reg); err != nil {
		return reg, err
	}
	return reg, nil
}

func validVersion(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '.' || r == '-' || r == '_' {
			continue
		}
		return false
	}
	return true
}

func validateDefaults(reg Registry) error {
	groups := map[string]map[string]map[string]string{}
	aliasFamilies := map[string]string{}
	for name, t := range reg.Tools {
		metadataCount := 0
		for _, value := range []string{t.DefaultFamily, t.DefaultVersion, t.DefaultAlias} {
			if value != "" {
				metadataCount++
			}
		}
		if metadataCount == 0 {
			continue
		}
		if reg.SchemaVersion < 2 {
			return fmt.Errorf("tool %q: default alias metadata requires schema_version = 2", name)
		}
		if metadataCount != 3 {
			return fmt.Errorf("tool %q: default_family, default_version and default_alias must be declared together", name)
		}
		if !ValidToolName(t.DefaultFamily) || !validVersion(t.DefaultVersion) || !ValidToolName(t.DefaultAlias) || ReservedToolName(t.DefaultAlias) {
			return fmt.Errorf("tool %q: invalid default alias metadata", name)
		}
		if _, collision := reg.Tools[t.DefaultAlias]; collision {
			return fmt.Errorf("tool %q: default_alias %q collides with a concrete tool profile", name, t.DefaultAlias)
		}
		if previous, duplicate := aliasFamilies[t.DefaultAlias]; duplicate && previous != t.DefaultFamily {
			return fmt.Errorf("default alias %q is declared by both %q and %q families", t.DefaultAlias, previous, t.DefaultFamily)
		}
		aliasFamilies[t.DefaultAlias] = t.DefaultFamily
		versions := groups[t.DefaultFamily]
		if versions == nil {
			versions = map[string]map[string]string{}
			groups[t.DefaultFamily] = versions
		}
		aliases := versions[t.DefaultVersion]
		if aliases == nil {
			aliases = map[string]string{}
			versions[t.DefaultVersion] = aliases
		}
		if previous, duplicate := aliases[t.DefaultAlias]; duplicate {
			return fmt.Errorf("tools %q and %q both supply default alias %q for %s %s", previous, name, t.DefaultAlias, t.DefaultFamily, t.DefaultVersion)
		}
		aliases[t.DefaultAlias] = name
	}
	if reg.SchemaVersion < 2 && len(reg.Defaults) > 0 {
		return errors.New("[defaults.FAMILY] sections require schema_version = 2")
	}
	for family, selected := range reg.Defaults {
		if selected == "" {
			return fmt.Errorf("default family %q: version is required", family)
		}
		versions := groups[family]
		selectedAliases, ok := versions[selected]
		if !ok {
			return fmt.Errorf("default family %q selects unavailable version %q", family, selected)
		}
		for version, aliases := range versions {
			if len(aliases) != len(selectedAliases) {
				return fmt.Errorf("default family %q version %q does not supply the same aliases as selected version %q", family, version, selected)
			}
			for alias := range selectedAliases {
				if _, ok := aliases[alias]; !ok {
					return fmt.Errorf("default family %q version %q is missing alias %q", family, version, alias)
				}
			}
		}
	}
	for family := range groups {
		if _, ok := reg.Defaults[family]; !ok {
			return fmt.Errorf("default alias profiles for family %q require a [defaults.%s] section", family, family)
		}
	}
	return nil
}

// Resolve returns the concrete tool selected for a concrete name or an
// unversioned default alias. The resolved name is always the stable concrete
// profile name; the returned Tool.Name remains the requested name so runtime
// errors point at the shim the user can actually update or inspect.
func (reg Registry) Resolve(name string) (tool Tool, resolved string, ok bool) {
	name = strings.ToLower(name)
	if t, exists := reg.Tools[name]; exists {
		return t, name, true
	}
	for family, version := range reg.Defaults {
		for concrete, t := range reg.Tools {
			if t.DefaultFamily == family && t.DefaultVersion == version && t.DefaultAlias == name {
				t.Name = name
				return t, concrete, true
			}
		}
	}
	return Tool{}, "", false
}

// ToolNames returns every invokable shim name, including virtual default aliases.
func (reg Registry) ToolNames() []string {
	seen := map[string]bool{}
	for name := range reg.Tools {
		seen[name] = true
	}
	for family, version := range reg.Defaults {
		for _, t := range reg.Tools {
			if t.DefaultFamily == family && t.DefaultVersion == version {
				seen[t.DefaultAlias] = true
			}
		}
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

type DefaultInfo struct {
	Family   string
	Selected string
	Versions []string
	Aliases  []string
}

func (reg Registry) DefaultInfo(family string) (DefaultInfo, bool) {
	family = strings.ToLower(family)
	selected, ok := reg.Defaults[family]
	if !ok {
		return DefaultInfo{}, false
	}
	versionsSet, aliasesSet := map[string]bool{}, map[string]bool{}
	for _, t := range reg.Tools {
		if t.DefaultFamily == family {
			versionsSet[t.DefaultVersion] = true
			aliasesSet[t.DefaultAlias] = true
		}
	}
	info := DefaultInfo{Family: family, Selected: selected}
	for version := range versionsSet {
		info.Versions = append(info.Versions, version)
	}
	for alias := range aliasesSet {
		info.Aliases = append(info.Aliases, alias)
	}
	sort.Strings(info.Versions)
	sort.Strings(info.Aliases)
	return info, true
}

func ValidToolName(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			continue
		}
		return false
	}
	return true
}

// ReservedToolName rejects names whose NAME.exe shim would collide with the
// cb binary itself, or which are Windows reserved device names (creating
// con.exe / nul.exe etc. misbehaves across Windows tooling).
func ReservedToolName(s string) bool {
	switch s {
	case "cb", "container-bin", "con", "prn", "aux", "nul":
		return true
	}
	// main() uses the same predicate for argv[0] dispatch, so a versioned cb
	// binary name can never collide with a tool shim.
	if IsVersionedBinaryName(s) {
		return true
	}
	if len(s) == 4 && (strings.HasPrefix(s, "com") || strings.HasPrefix(s, "lpt")) && s[3] >= '1' && s[3] <= '9' {
		return true
	}
	return false
}

// IsVersionedBinaryName recognizes release binary names such as cb-v1.2.3.
// Requiring a digit immediately after cb-v keeps ordinary tool names such as
// cb-vault available while preserving versioned management-binary dispatch.
func IsVersionedBinaryName(s string) bool {
	return len(s) > len("cb-v") && strings.HasPrefix(s, "cb-v") && s[len("cb-v")] >= '0' && s[len("cb-v")] <= '9'
}

func validEnvAssignment(s string) bool {
	i := strings.IndexByte(s, '=')
	if i <= 0 {
		return false
	}
	name := s[:i]
	for j, r := range name {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || r == '_' || (j > 0 && r >= '0' && r <= '9') {
			continue
		}
		return false
	}
	return true
}

func ParseVolumeBinding(spec string) (string, string, error) {
	i := strings.Index(spec, ":/")
	if i <= 0 {
		return "", "", errors.New("expected NAME:/absolute/container/path")
	}
	name, dst := spec[:i], spec[i+1:]
	if !ValidToolName(name) {
		return "", "", fmt.Errorf("invalid volume name %q", name)
	}
	if !strings.HasPrefix(dst, "/") {
		return "", "", errors.New("container path must be absolute")
	}
	for _, seg := range strings.Split(dst, "/") {
		if seg == ".." {
			return "", "", fmt.Errorf("container path %q must not contain \"..\"", dst)
		}
	}
	cleanDst := path.Clean(dst)
	if cleanDst == "/" {
		return "", "", errors.New("container path must not be the filesystem root")
	}
	// Stateful volume declarations are expected to use locations chosen by
	// the profile, but the legacy python provider owns these two fixed paths.
	// Letting a project/shared volume claim either path (or a child of it)
	// creates a duplicate or partially shadowed provider mount at run time.
	for _, reserved := range []string{"/venv", "/root/.cache/pip"} {
		if pathContainsOrEquals(reserved, cleanDst) {
			return "", "", fmt.Errorf("container path %q is reserved for python provider state", dst)
		}
	}
	return name, dst, nil
}

// ParseHostMount splits a "SOURCE:/container/path:MODE" host_mounts entry.
// The source/target delimiter reuses ParseVolumeBinding's ":/" convention: a
// Windows source path's drive-letter colon is always followed by a backslash,
// never a forward slash, so the first ":/" in the string unambiguously marks
// the boundary before the container path even when the source itself (e.g.
// "D:\Video") contains a colon of its own.
func ParseHostMount(spec string) (source, target, mode string, err error) {
	i := strings.Index(spec, ":/")
	if i <= 0 {
		return "", "", "", errors.New("expected SOURCE:/absolute/container/path:ro or SOURCE:/absolute/container/path:rw")
	}
	source = spec[:i]
	rest := spec[i+1:] // "/container/path:MODE"
	j := strings.LastIndex(rest, ":")
	if j < 0 {
		return "", "", "", errors.New("host_mounts entry is missing a :ro or :rw mode suffix")
	}
	target = rest[:j]
	mode = rest[j+1:]
	if mode != "ro" && mode != "rw" {
		return "", "", "", fmt.Errorf("host_mounts mode must be \"ro\" or \"rw\", got %q", mode)
	}
	if !strings.HasPrefix(target, "/") {
		return "", "", "", errors.New("host_mounts container path must be absolute")
	}
	if strings.Contains(target, ",") {
		// Mirrors the source comma check below: dockerrun.MountSpecMode would
		// reject this too, but only at RunTool time, once the tool is
		// actually invoked. Catching it here moves the failure to registry
		// load, matching this task's two-stage validation split (structural
		// checks at load, environment-dependent checks at run).
		return "", "", "", errors.New("host_mounts target contains a comma and cannot be represented safely in docker --mount syntax (values are comma-separated with no escaping)")
	}
	if strings.Contains(target, ":") {
		// The mode suffix is found by taking the LAST ":" in the remainder
		// (see below), so an entry with an extra colon inside the target,
		// e.g. "D:\V:/root/a:b:ro", parses without error today: the LAST
		// colon is still correctly found as the mode delimiter, but the
		// target itself is left containing one. Docker's --mount tolerates a
		// colon in dst=, so this was never a mis-mount risk, but it's an
		// unintended shape the documented SOURCE:/CONTAINER_PATH:MODE grammar
		// doesn't describe. Rejecting it keeps the grammar as tight as every
		// other part of this validation.
		return "", "", "", errors.New("host_mounts target must not contain \":\"")
	}
	// Reject ".." path segments outright, before cleaning: path.Clean collapses
	// a traversal like "/workspace/.." to "/", which is not itself in the
	// reserved-namespace list validateHostMounts checks against, so a naive
	// "clean, then compare against reserved prefixes" order would let a
	// declared target ESCAPE the very check it's meant to satisfy. There is no
	// legitimate reason for a host_mounts target to contain "..": it should
	// always be a direct absolute container path the profile author wrote
	// intentionally. Failing this loudly, before any normalization, keeps the
	// reserved-namespace check meaningful regardless of what "." segments
	// (which ARE legitimate, e.g. for collision-detection equivalence) get
	// cleaned away afterward.
	for _, seg := range strings.Split(target, "/") {
		if seg == ".." {
			return "", "", "", fmt.Errorf("host_mounts container path %q must not contain \"..\"", target)
		}
	}
	target = path.Clean(target)
	// Defense in depth: no legal traversal-free target should ever clean to
	// bare "/" (the shortest reserved path is a single segment below root),
	// but reject it explicitly rather than relying on that reasoning holding
	// forever as the reserved-namespace list evolves. A host_mounts entry at
	// "/" would shadow every container-bin-managed mount.
	if target == "/" {
		return "", "", "", errors.New("host_mounts container path must not be the filesystem root")
	}
	if source == "" {
		return "", "", "", errors.New("host_mounts source must not be empty")
	}
	if strings.Contains(source, ",") {
		return "", "", "", errors.New("host_mounts source contains a comma and cannot be represented safely in docker --mount syntax (values are comma-separated with no escaping)")
	}
	if err := validHostMountSource(source); err != nil {
		return "", "", "", err
	}
	return source, target, mode, nil
}

func validHostMountSource(source string) error {
	if strings.Contains(source, "%") {
		if !strings.HasPrefix(source, "%USERPROFILE%") {
			return errors.New("host_mounts source contains an unsupported %-variable; only %USERPROFILE% is recognized")
		}
		rest := source[len("%USERPROFILE%"):]
		if strings.Contains(rest, "%") {
			return errors.New("host_mounts source contains an unsupported %-variable after %USERPROFILE%")
		}
		// %USERPROFILE% must be the whole source, or immediately followed by a
		// path separator. ExpandHostMountSource does plain string
		// concatenation of os.UserHomeDir() with whatever follows the token,
		// so without this, "%USERPROFILE%foo" would resolve to a *sibling* of
		// the home directory (e.g. C:\Users\<user>foo) rather than a child of
		// it -- silently not the path the registry line visually suggests.
		if rest != "" && rest[0] != '\\' && rest[0] != '/' {
			return errors.New("host_mounts source must be exactly %USERPROFILE% or followed immediately by \\ or /")
		}
		return nil
	}
	if isWindowsAbsPath(source) {
		return nil
	}
	return errors.New("host_mounts source must be %USERPROFILE%\\... or an absolute Windows path (X:\\...)")
}

func isWindowsAbsPath(s string) bool {
	if len(s) < 3 {
		return false
	}
	c := s[0]
	isLetter := (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')
	return isLetter && s[1] == ':' && (s[2] == '\\' || s[2] == '/')
}

// pathContainsOrEquals reports whether target is parent itself, or a strict
// descendant of it. Both arguments must already be path.Clean'd absolute
// POSIX container paths. Used only for the fixed, cb-owned reserved
// namespaces (/workspace, /cb, /venv, /root/.cache/pip) -- not for arbitrary
// project_volumes/shared_volumes destinations, where a host_mounts entry
// nested under a user-declared volume is a normal, valid Docker
// configuration (the more specific mount just shadows part of the outer
// one), not a defect to reject.
func pathContainsOrEquals(parent, target string) bool {
	return target == parent || strings.HasPrefix(target, parent+"/")
}

func validateHostMounts(t Tool) error {
	// project_volumes and shared_volumes are both checked here, not just
	// shared_volumes: ParseVolumeBinding places no requirement that a
	// project_volumes destination live under /workspace (that is only true
	// by convention for this repo's built-in profiles), so a custom profile
	// declaring e.g. project_volumes = ["foo:/root/.foo"] could otherwise
	// collide with a host_mounts target at that same literal path with
	// nothing catching it.
	volumeDst := map[string]bool{}
	for _, spec := range append(append([]string{}, t.ProjectVolumes...), t.SharedVolumes...) {
		_, dst, err := ParseVolumeBinding(spec)
		if err != nil {
			return err // already validated earlier in the same loop; defensive only
		}
		volumeDst[path.Clean(dst)] = true
	}
	seen := map[string]bool{}
	for _, spec := range t.HostMounts {
		_, target, _, err := ParseHostMount(spec)
		if err != nil {
			return err
		}
		// Prefix-based, not exact-match: /venv and /root/.cache/pip are fixed,
		// semantically load-bearing paths the python provider's bootstrap
		// script depends on having their full structure intact (it checks
		// /venv/bin/python specifically), not just their top-level directory.
		// An exact-match-only reservation would let a target like /venv/bin
		// validate cleanly and only break the tool at run time with no
		// explanatory error -- the same shape of gap /workspace and /cb were
		// already guarded against with HasPrefix, extended here to all four
		// reserved namespaces uniformly via pathContainsOrEquals.
		for _, reserved := range []string{"/workspace", "/cb", "/venv", "/root/.cache/pip"} {
			if pathContainsOrEquals(reserved, target) {
				return fmt.Errorf("host_mounts target %q is reserved for container-bin's own workspace/state mounts", target)
			}
		}
		if seen[target] {
			return fmt.Errorf("host_mounts target %q is declared more than once", target)
		}
		seen[target] = true
		if volumeDst[target] {
			return fmt.Errorf("host_mounts target %q collides with a project_volumes/shared_volumes destination", target)
		}
	}
	return nil
}

func ListTools(reg Registry, cfgPath string) {
	names := reg.ToolNames()
	fmt.Printf("registry: %s\nschema:   %d\n\n", cfgPath, reg.SchemaVersion)
	for _, n := range names {
		t, resolved, _ := reg.Resolve(n)
		detail := t.Provider
		if t.Role != "" {
			detail += "/" + t.Role
		}
		if resolved != n {
			detail += " -> " + resolved
		}
		fmt.Printf("%-10s  %-32s  %s\n", n, t.Image, detail)
	}
}
