// Package registry owns the container-bin tool registry: the Tool/Registry
// types, the TOML subset parser that reads container-bin.toml, the built-in
// default profiles, and the on-disk registry lifecycle.
package registry

import (
	"bufio"
	"errors"
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/AviBackToBlack/container-bin/internal/toml"
)

// Tool is deliberately generic. Provider owns lifecycle/state semantics;
// Command is prepended inside the container. An empty Command means: use the
// image ENTRYPOINT as-is (handy for images such as ghcr.io/jqlang/jq).
type Tool struct {
	Name           string
	Image          string
	Provider       string // stateless, python
	Role           string // provider-specific: python, pip
	Command        []string
	ArgsPrefix     []string
	PathNext       []string // options whose following argv is a path
	PathEquals     []string // options of the form --opt=PATH
	PathLast       bool     // final non-option argv is a path
	PathLastIfAny  []string // apply PathLast only when any listed argv is present
	EnvPrefixes    []string // host env var prefixes passed into the container
	EnvNames       []string // exact host env var names passed into the container
	EnvSet         []string // literal NAME=VALUE entries injected into the container
	ProjectMarkers []string // tool/provider-specific project root markers
	StateGroup     string   // stable namespace shared by related stateful tools
	ProjectVolumes []string // NAME:CONTAINER_PATH, project-scoped named volumes
	SharedVolumes  []string // NAME:CONTAINER_PATH, shared named volumes
	HostMounts     []string // SOURCE:/CONTAINER_PATH:ro|rw, explicit host bind mounts
}

type Registry struct {
	SchemaVersion int
	Tools         map[string]Tool
}

const DefaultTOML = `# container-bin tool registry
schema_version = 1
# Generated by cb. Edit this file, then run: cb install
#
# provider = "stateless" => disposable container, no tool-specific state
# provider = "python"    => legacy Python provider: project /venv + shared pip cache
# provider = "stateful"  => generic declarative persistent volumes
#
# Tool-semantics rules:
# path_next   = ["-i"]       => argv immediately following this option is a host path
# path_equals = ["-chdir"]   => -chdir=HOST_PATH is rewritten safely
# path_last   = true          => final non-option argv is treated as a host path
# path_last_if_any = ["-i"]  => path_last only applies if one of these argv exists
# env_prefixes / env_names   => explicitly pass selected host environment variables
# env_set                    => literal NAME=VALUE entries injected into the container
# project_markers            => files/dirs used to find this tool's project root
# state_group                => namespace shared by related stateful shims
# project_volumes            => ["name:/container/path"] scoped by project root
# shared_volumes             => ["name:/container/path"] shared across projects
# host_mounts                => ["%USERPROFILE%\\.claude:/root/.claude:ro"] explicit host bind mounts

[tools.python]
image = "python:3.13-slim"
provider = "python"
role = "python"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.python3]
image = "python:3.13-slim"
provider = "python"
role = "python"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.pip]
image = "python:3.13-slim"
provider = "python"
role = "pip"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.pip3]
image = "python:3.13-slim"
provider = "python"
role = "pip"
project_markers = ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", ".git"]

[tools.jq]
image = "ghcr.io/jqlang/jq:latest"
provider = "stateless"

[tools.yq]
image = "mikefarah/yq:latest"
provider = "stateless"
env_names = ["NO_COLOR"]

[tools.terraform]
image = "hashicorp/terraform:latest"
provider = "stateless"
path_equals = ["-chdir"]
env_prefixes = ["TF_", "AWS_", "ARM_", "AZURE_", "GOOGLE_", "GCLOUD_", "CLOUDFLARE_", "HCLOUD_", "DIGITALOCEAN_", "LINODE_", "OVH_", "VAULT_", "CONSUL_"]
env_names = ["HOME", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.ffmpeg]
image = "lscr.io/linuxserver/ffmpeg:latest"
provider = "stateless"
# Intentionally no forced path rules: FFmpeg inputs can also be URLs, pipes,
# devices and lavfi expressions. Generic host-path detection is safer.

[tools.node]
image = "node:24-slim"
provider = "stateful"
command = ["node"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "NPM_CONFIG_REGISTRY", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npm]
image = "node:24-slim"
provider = "stateful"
command = ["npm"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npx]
image = "node:24-slim"
provider = "stateful"
command = ["npx"]
state_group = "node24"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.node22]
image = "node:22-slim"
provider = "stateful"
command = ["node"]
state_group = "node22"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "NPM_CONFIG_REGISTRY", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npm22]
image = "node:22-slim"
provider = "stateful"
command = ["npm"]
state_group = "node22"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.npx22]
image = "node:22-slim"
provider = "stateful"
command = ["npx"]
state_group = "node22"
project_markers = ["package.json", "package-lock.json", "npm-shrinkwrap.json", ".git"]
project_volumes = ["node-modules:/workspace/node_modules"]
shared_volumes = ["npm-cache:/root/.npm", "npm-global:/cb/npm-global"]
env_set = ["NPM_CONFIG_PREFIX=/cb/npm-global"]
env_prefixes = ["NPM_CONFIG_"]
env_names = ["NODE_ENV", "NODE_OPTIONS", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.go]
image = "golang:1.24"
provider = "stateful"
command = ["go"]
state_group = "go124"
project_markers = ["go.mod", "go.work", ".git"]
shared_volumes = ["gomodcache:/go/pkg/mod", "gobuild:/root/.cache/go-build", "gobin:/go/bin"]
# No path_next: everything after 'go run PKG' is handed to the user's program, so
# forcing the value after -o/-C would rewrite ordinary flags such as 'go run . -o json'
# into container paths. Real output paths are already mapped by the general rules
# (absolute and .\rel forms), and a bare name resolves against the container working
# directory, which is the project.
# Do not allowlist path-valued variables; Windows paths are meaningless inside the Linux container
env_names = ["GOFLAGS", "GOPROXY", "GONOPROXY", "GOPRIVATE", "GOSUMDB", "GONOSUMDB", "GOINSECURE", "GOOS", "GOARCH", "GOARM", "CGO_ENABLED", "GOTOOLCHAIN", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]

[tools.gofmt]
image = "golang:1.24"
provider = "stateful"
command = ["gofmt"]
state_group = "go124"
project_markers = ["go.mod", "go.work", ".git"]
shared_volumes = ["gomodcache:/go/pkg/mod", "gobuild:/root/.cache/go-build", "gobin:/go/bin"]
# No path_last: a bare final argument like the value of -r is not a file, and real
# file operands are already mapped by the general path-shape rules.
# Do not allowlist path-valued variables; Windows paths are meaningless inside the Linux container
env_names = ["GOFLAGS", "GOPROXY", "GONOPROXY", "GOPRIVATE", "GOSUMDB", "GONOSUMDB", "GOINSECURE", "GOOS", "GOARCH", "GOARM", "CGO_ENABLED", "GOTOOLCHAIN", "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "http_proxy", "https_proxy", "no_proxy"]
`

func Default() Registry {
	reg, err := ParseTOML(DefaultTOML)
	if err != nil {
		panic("invalid built-in registry: " + err.Error())
	}
	return reg
}

func DefaultToolSections() map[string]string {
	sections := map[string]string{}
	var current string
	var b strings.Builder
	flush := func() {
		if current != "" {
			sections[current] = "\n" + b.String()
		}
		b.Reset()
	}
	for _, line := range strings.Split(DefaultTOML, "\n") {
		trim := strings.TrimSpace(line)
		if strings.HasPrefix(trim, "[tools.") && strings.HasSuffix(trim, "]") {
			flush()
			current = strings.TrimSuffix(strings.TrimPrefix(trim, "[tools."), "]")
		}
		if current != "" {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	flush()
	return sections
}

// ParseTOML intentionally supports only the tiny TOML subset used by
// container-bin's registry: [tools.NAME], quoted strings and arrays of quoted
// strings. Rejecting unknown syntax is safer than silently misreading config.
func ParseTOML(s string) (Registry, error) {
	reg := Registry{SchemaVersion: 1, Tools: map[string]Tool{}}
	// currentName is the [tools.NAME] section being parsed, or "" before the
	// first section. A name is never empty here because ValidToolName rejects
	// that, so "" is an unambiguous "no section yet" marker.
	var currentName string
	scanner := bufio.NewScanner(strings.NewReader(s))
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(toml.StripComment(scanner.Text()))
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "[") {
			if !strings.HasSuffix(line, "]") {
				return reg, fmt.Errorf("line %d: malformed section", lineNo)
			}
			sec := strings.TrimSpace(line[1 : len(line)-1])
			if !strings.HasPrefix(sec, "tools.") || len(sec) <= len("tools.") {
				return reg, fmt.Errorf("line %d: only [tools.NAME] sections are supported", lineNo)
			}
			name := strings.ToLower(strings.TrimSpace(strings.TrimPrefix(sec, "tools.")))
			if !ValidToolName(name) {
				return reg, fmt.Errorf("line %d: invalid tool name %q", lineNo, name)
			}
			if ReservedToolName(name) {
				return reg, fmt.Errorf("line %d: tool name %q is reserved (would collide with cb itself or a Windows device name); rename or delete the [tools.%s] section in the registry file to recover", lineNo, name, name)
			}
			if _, dup := reg.Tools[name]; dup {
				return reg, fmt.Errorf("line %d: duplicate [tools.%s] section", lineNo, name)
			}
			reg.Tools[name] = Tool{Name: name, Provider: "stateless"}
			currentName = name
			continue
		}
		if currentName == "" {
			kv := strings.SplitN(line, "=", 2)
			if len(kv) == 2 && strings.TrimSpace(kv[0]) == "schema_version" {
				v, err := strconv.Atoi(strings.TrimSpace(kv[1]))
				if err != nil || v < 1 {
					return reg, fmt.Errorf("line %d: invalid schema_version", lineNo)
				}
				if v > 1 {
					return reg, fmt.Errorf("line %d: registry schema_version %d is newer than this cb supports (max 1)", lineNo, v)
				}
				reg.SchemaVersion = v
				continue
			}
			return reg, fmt.Errorf("line %d: key outside [tools.NAME] section", lineNo)
		}
		kv := strings.SplitN(line, "=", 2)
		if len(kv) != 2 {
			return reg, fmt.Errorf("line %d: expected key = value", lineNo)
		}
		key := strings.TrimSpace(kv[0])
		value := strings.TrimSpace(kv[1])
		t := reg.Tools[currentName]
		switch key {
		case "image":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d image: %w", lineNo, err)
			}
			t.Image = v
		case "provider":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d provider: %w", lineNo, err)
			}
			t.Provider = strings.ToLower(v)
		case "role":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d role: %w", lineNo, err)
			}
			t.Role = strings.ToLower(v)
		case "command":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d command: %w", lineNo, err)
			}
			t.Command = v
		case "args_prefix":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d args_prefix: %w", lineNo, err)
			}
			t.ArgsPrefix = v
		case "path_next":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_next: %w", lineNo, err)
			}
			t.PathNext = v
		case "path_equals":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_equals: %w", lineNo, err)
			}
			t.PathEquals = v
		case "path_last":
			v, err := toml.ParseBool(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_last: %w", lineNo, err)
			}
			t.PathLast = v
		case "path_last_if_any":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d path_last_if_any: %w", lineNo, err)
			}
			t.PathLastIfAny = v
		case "env_prefixes":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_prefixes: %w", lineNo, err)
			}
			t.EnvPrefixes = v
		case "env_names":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_names: %w", lineNo, err)
			}
			t.EnvNames = v
		case "env_set":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d env_set: %w", lineNo, err)
			}
			for _, kv := range v {
				if !validEnvAssignment(kv) {
					return reg, fmt.Errorf("line %d env_set: invalid NAME=VALUE %q", lineNo, kv)
				}
			}
			t.EnvSet = v
		case "project_markers":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d project_markers: %w", lineNo, err)
			}
			t.ProjectMarkers = v
		case "state_group":
			v, err := toml.ParseQuoted(value)
			if err != nil {
				return reg, fmt.Errorf("line %d state_group: %w", lineNo, err)
			}
			t.StateGroup = strings.ToLower(v)
		case "project_volumes":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d project_volumes: %w", lineNo, err)
			}
			t.ProjectVolumes = v
		case "shared_volumes":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d shared_volumes: %w", lineNo, err)
			}
			t.SharedVolumes = v
		case "host_mounts":
			v, err := toml.ParseStringArray(value)
			if err != nil {
				return reg, fmt.Errorf("line %d host_mounts: %w", lineNo, err)
			}
			t.HostMounts = v
		default:
			return reg, fmt.Errorf("line %d: unsupported key %q", lineNo, key)
		}
		reg.Tools[currentName] = t
	}
	if err := scanner.Err(); err != nil {
		return reg, err
	}
	if len(reg.Tools) == 0 {
		return reg, errors.New("registry contains no tools")
	}
	for name, t := range reg.Tools {
		if t.Image == "" {
			return reg, fmt.Errorf("tool %q: image is required", name)
		}
		switch t.Provider {
		case "stateless":
		case "python":
			if t.Role != "python" && t.Role != "pip" {
				return reg, fmt.Errorf("tool %q: python provider requires role = \"python\" or \"pip\"", name)
			}
		case "stateful":
			if t.StateGroup == "" {
				return reg, fmt.Errorf("tool %q: stateful provider requires state_group", name)
			}
			if len(t.ProjectVolumes) == 0 && len(t.SharedVolumes) == 0 {
				return reg, fmt.Errorf("tool %q: stateful provider requires at least one volume", name)
			}
			for _, spec := range append(append([]string{}, t.ProjectVolumes...), t.SharedVolumes...) {
				if _, _, err := ParseVolumeBinding(spec); err != nil {
					return reg, fmt.Errorf("tool %q volume %q: %w", name, spec, err)
				}
			}
		default:
			return reg, fmt.Errorf("tool %q: unsupported provider %q", name, t.Provider)
		}
		if err := validateHostMounts(t); err != nil {
			return reg, fmt.Errorf("tool %q: %w", name, err)
		}
	}
	return reg, nil
}

func ValidToolName(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			continue
		}
		return false
	}
	return true
}

// ReservedToolName rejects names whose NAME.exe shim would collide with the
// cb binary itself, or which are Windows reserved device names (creating
// con.exe / nul.exe etc. misbehaves across Windows tooling).
func ReservedToolName(s string) bool {
	switch s {
	case "cb", "container-bin", "con", "prn", "aux", "nul":
		return true
	}
	// main() treats any argv[0] starting with "cb-v" as the management CLI
	// (versioned binary names), so such a shim could never dispatch to a tool.
	if strings.HasPrefix(s, "cb-v") {
		return true
	}
	if len(s) == 4 && (strings.HasPrefix(s, "com") || strings.HasPrefix(s, "lpt")) && s[3] >= '1' && s[3] <= '9' {
		return true
	}
	return false
}

func validEnvAssignment(s string) bool {
	i := strings.IndexByte(s, '=')
	if i <= 0 {
		return false
	}
	name := s[:i]
	for j, r := range name {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || r == '_' || (j > 0 && r >= '0' && r <= '9') {
			continue
		}
		return false
	}
	return true
}

func ParseVolumeBinding(spec string) (string, string, error) {
	i := strings.Index(spec, ":/")
	if i <= 0 {
		return "", "", errors.New("expected NAME:/absolute/container/path")
	}
	name, dst := spec[:i], spec[i+1:]
	if !ValidToolName(name) {
		return "", "", fmt.Errorf("invalid volume name %q", name)
	}
	if !strings.HasPrefix(dst, "/") {
		return "", "", errors.New("container path must be absolute")
	}
	return name, dst, nil
}

// ParseHostMount splits a "SOURCE:/container/path:MODE" host_mounts entry.
// The source/target delimiter reuses ParseVolumeBinding's ":/" convention: a
// Windows source path's drive-letter colon is always followed by a backslash,
// never a forward slash, so the first ":/" in the string unambiguously marks
// the boundary before the container path even when the source itself (e.g.
// "D:\Video") contains a colon of its own.
func ParseHostMount(spec string) (source, target, mode string, err error) {
	i := strings.Index(spec, ":/")
	if i <= 0 {
		return "", "", "", errors.New("expected SOURCE:/absolute/container/path:ro or SOURCE:/absolute/container/path:rw")
	}
	source = spec[:i]
	rest := spec[i+1:] // "/container/path:MODE"
	j := strings.LastIndex(rest, ":")
	if j < 0 {
		return "", "", "", errors.New("host_mounts entry is missing a :ro or :rw mode suffix")
	}
	target = rest[:j]
	mode = rest[j+1:]
	if mode != "ro" && mode != "rw" {
		return "", "", "", fmt.Errorf("host_mounts mode must be \"ro\" or \"rw\", got %q", mode)
	}
	if !strings.HasPrefix(target, "/") {
		return "", "", "", errors.New("host_mounts container path must be absolute")
	}
	target = path.Clean(target)
	if source == "" {
		return "", "", "", errors.New("host_mounts source must not be empty")
	}
	if strings.Contains(source, ",") {
		return "", "", "", errors.New("host_mounts source contains a comma and cannot be represented safely in docker --mount syntax (values are comma-separated with no escaping)")
	}
	if err := validHostMountSource(source); err != nil {
		return "", "", "", err
	}
	return source, target, mode, nil
}

func validHostMountSource(source string) error {
	if strings.Contains(source, "%") {
		if !strings.HasPrefix(source, "%USERPROFILE%") {
			return errors.New("host_mounts source contains an unsupported %-variable; only %USERPROFILE% is recognized")
		}
		if strings.Contains(source[len("%USERPROFILE%"):], "%") {
			return errors.New("host_mounts source contains an unsupported %-variable after %USERPROFILE%")
		}
		return nil
	}
	if isWindowsAbsPath(source) {
		return nil
	}
	return errors.New("host_mounts source must be %USERPROFILE%\\... or an absolute Windows path (X:\\...)")
}

func isWindowsAbsPath(s string) bool {
	if len(s) < 3 {
		return false
	}
	c := s[0]
	isLetter := (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')
	return isLetter && s[1] == ':' && (s[2] == '\\' || s[2] == '/')
}

func validateHostMounts(t Tool) error {
	// project_volumes and shared_volumes are both checked here, not just
	// shared_volumes: ParseVolumeBinding places no requirement that a
	// project_volumes destination live under /workspace (that is only true
	// by convention for this repo's built-in profiles), so a custom profile
	// declaring e.g. project_volumes = ["foo:/root/.foo"] could otherwise
	// collide with a host_mounts target at that same literal path with
	// nothing catching it.
	volumeDst := map[string]bool{}
	for _, spec := range append(append([]string{}, t.ProjectVolumes...), t.SharedVolumes...) {
		_, dst, err := ParseVolumeBinding(spec)
		if err != nil {
			return err // already validated earlier in the same loop; defensive only
		}
		volumeDst[path.Clean(dst)] = true
	}
	seen := map[string]bool{}
	for _, spec := range t.HostMounts {
		_, target, _, err := ParseHostMount(spec)
		if err != nil {
			return err
		}
		if target == "/workspace" || strings.HasPrefix(target, "/workspace/") ||
			target == "/cb" || strings.HasPrefix(target, "/cb/") ||
			target == "/venv" || target == "/root/.cache/pip" {
			return fmt.Errorf("host_mounts target %q is reserved for container-bin's own workspace/state mounts", target)
		}
		if seen[target] {
			return fmt.Errorf("host_mounts target %q is declared more than once", target)
		}
		seen[target] = true
		if volumeDst[target] {
			return fmt.Errorf("host_mounts target %q collides with a project_volumes/shared_volumes destination", target)
		}
	}
	return nil
}

func ListTools(reg Registry, cfgPath string) {
	names := make([]string, 0, len(reg.Tools))
	for n := range reg.Tools {
		names = append(names, n)
	}
	sort.Strings(names)
	fmt.Printf("registry: %s\nschema:   %d\n\n", cfgPath, reg.SchemaVersion)
	for _, n := range names {
		t := reg.Tools[n]
		detail := t.Provider
		if t.Role != "" {
			detail += "/" + t.Role
		}
		fmt.Printf("%-10s  %-32s  %s\n", t.Name, t.Image, detail)
	}
}
